import { Given, When, Then } from '@cucumber/cucumber';
import assert from 'node:assert/strict';
import { checkConformance } from '../../tools/spec-graph/conformance.ts';
import { buildReadinessInventory } from '../../tools/spec-graph/readiness-inventory.ts';
import { buildToolRegistry } from '../../tools/spec-mcp-server/tools.ts';
import { openDatabase } from '../../tools/spec-mcp-server/sqlite/wrapper.ts';
import { persistGraph, loadGraph } from '../../tools/spec-mcp-server/sqlite/persist.ts';
import type { NfrNode, ScenarioNode, SpecGraph } from '../../tools/spec-graph/types.ts';
import { V4World } from '../hooks/before-after.ts';

interface NfrWorld extends V4World { graph?: SpecGraph; findings?: ReturnType<typeof checkConformance>; inventory?: ReturnType<typeof buildReadinessInventory>; restored?: SpecGraph | null; methods?: string[]; }
const nfr = (id: string, method: 'test' | 'analysis' | 'review' | 'inspection' | 'demonstration', obligation: 'required' | 'optional' | 'not-applicable' = 'required'): NfrNode => ({ id, type: 'NFR', spec: 'fixture', file: '.specs/fixture/NFR.md', line: 1, title: id, anchors: [id], body: '', metadata: { schemaVersion: 1, verificationMethod: method, risks: [], demands: [{ type: 'integration-test', obligation }], _unknown: {} } });
const scenario = (id: string, tag: string, result?: ScenarioNode['lastResult']): ScenarioNode => ({ id, type: 'Scenario', spec: 'fixture', file: '.specs/fixture/fixture.feature', line: 1, tags: [tag], steps: [], lastResult: result });
function graph(nodes: Array<NfrNode | ScenarioNode>, edges: SpecGraph['edges']): SpecGraph { return { version: 1, builtAt: new Date(0).toISOString(), nodes: new Map(nodes.map((n) => [n.id, n])), edges, definitions: new Map(), backlinks: new Map(), endpointViolations: [] }; }

Given('a required NFR with its own tagged and passing scenario', function (this: NfrWorld) { const n = nfr('fixture:NFR-Performance-1', 'test'); const s = scenario('fixture:SCEN-nfr', '@NFR-Performance-1', 'PASSED'); this.graph = graph([n, s], [{ from: n.id, to: s.id, type: 'tested-by' }, { from: s.id, to: n.id, type: 'verifies' }, { from: s.id, to: `RESULT-${s.id}-PASSED`, type: 'last-result' }]); });
Given('one required NFR with no scenario and another with no passing scenario', function (this: NfrWorld) { const a = nfr('fixture:NFR-Required-1', 'test'); const b = nfr('fixture:NFR-Required-2', 'review'); const s = scenario('fixture:SCEN-nfr-fail', '@NFR-Required-2', 'FAILED'); this.graph = graph([a, b, s], [{ from: b.id, to: s.id, type: 'tested-by' }, { from: s.id, to: b.id, type: 'verifies' }, { from: s.id, to: `RESULT-${s.id}-FAILED`, type: 'last-result' }]); });
Given('required optional and justified not-applicable NFRs', function (this: NfrWorld) { const req = nfr('fixture:NFR-required', 'test'); const opt = nfr('fixture:NFR-optional', 'analysis', 'optional'); const na = nfr('fixture:NFR-na', 'inspection', 'not-applicable'); this.graph = graph([req, opt, na], []); });
Given('NFR fixtures using test analysis review inspection and demonstration methods', function (this: NfrWorld) { const methods: Array<'test' | 'analysis' | 'review' | 'inspection' | 'demonstration'> = ['test', 'analysis', 'review', 'inspection', 'demonstration']; const nodes = methods.map((m, i) => nfr(`fixture:NFR-${i + 1}`, m)); this.methods = methods; this.graph = graph(nodes, []); });
When('I build the spec-scoped readiness inventory', function (this: NfrWorld) { this.inventory = buildReadinessInventory(this.graph!, { spec: 'fixture' }); });
When('I round-trip them through parser MCP query and SQLite restore', async function (this: NfrWorld) { const tool = buildToolRegistry(() => this.graph!).find((t) => t.name === 'policy_query_requirements')!; const body = JSON.parse((await tool.handler({ spec: 'fixture' } as never)).content[0].text) as { results: Array<{ metadata: { verificationMethod?: string } }> }; assert.deepEqual(body.results.map((r) => r.metadata.verificationMethod).sort(), [...this.methods!].sort()); const handle = await openDatabase({ repoRoot: this.tempDir }); assert.equal(handle.backend.available, true); persistGraph(handle, this.graph!, 'nfr-methods'); this.restored = loadGraph(handle, 'nfr-methods'); handle.backend.close(); });
Then('the NFR and its tested-by and verifies edges remain in the inventory', function (this: NfrWorld) { assert.equal(this.inventory!.frs.length, 0); assert.equal(this.inventory!.nfr_satisfaction.required, 1); assert.ok(this.graph!.edges.some((e) => e.type === 'tested-by')); assert.ok(this.graph!.edges.some((e) => e.type === 'verifies')); });
Then('UNCOVERED_NFR and UNVERIFIED_NFR are reported as errors', function (this: NfrWorld) { assert.ok(this.findings!.some((f) => f.code === 'UNCOVERED_NFR' && f.severity === 'error')); assert.ok(this.findings!.some((f) => f.code === 'UNVERIFIED_NFR' && f.severity === 'error')); });
Then('NFR_SATISFACTION depends on every required NFR and keeps the others visible', function (this: NfrWorld) { assert.equal(this.inventory!.nfr_satisfaction.status, 'RED'); assert.equal(this.inventory!.nfr_satisfaction.required, 1); assert.deepEqual(this.inventory!.nfr_satisfaction.optional, ['NFR-optional']); assert.deepEqual(this.inventory!.nfr_satisfaction.not_applicable, ['NFR-na']); });
Then('every surface returns the same method and evaluated evidence state', function (this: NfrWorld) { assert.ok(this.restored); assert.deepEqual([...this.restored!.nodes.values()].filter((n) => n.type === 'NFR').map((n) => n.metadata?.verificationMethod).sort(), [...this.methods!].sort()); });
