import { Given, When, Then } from '@cucumber/cucumber';
import assert from 'node:assert/strict';
import { checkConformance } from '../../tools/spec-graph/conformance.ts';
import { buildReadinessInventory, evaluateReadiness } from '../../tools/spec-graph/readiness-inventory.ts';
import type { AcNode, FrNode, ScenarioNode, SpecGraph } from '../../tools/spec-graph/types.ts';
import { V4World } from '../hooks/before-after.ts';

interface ReadinessWorld extends V4World { graph?: SpecGraph; findings?: ReturnType<typeof checkConformance>; inventory?: ReturnType<typeof buildReadinessInventory>; }
const fr = (id: string): FrNode => ({ id, type: 'FR', spec: 'fixture', file: '.specs/fixture/FR.md', line: 1, title: id, anchors: [id], body: '' });
const ac = (id: string, parentFr: string): AcNode => ({ id, type: 'AC', spec: 'fixture', file: '.specs/fixture/ACCEPTANCE_CRITERIA.md', line: 1, parentFr, ears: '' });
const scen = (id: string, tags: string[], result?: ScenarioNode['lastResult']): ScenarioNode => ({ id, type: 'Scenario', spec: 'fixture', file: '.specs/fixture/fixture.feature', line: 1, tags, steps: [], lastResult: result });
function graph(nodes: Array<FrNode | AcNode | ScenarioNode>, edges: SpecGraph['edges']): SpecGraph { return { version: 1, builtAt: new Date(0).toISOString(), nodes: new Map(nodes.map((n) => [n.id, n])), edges, definitions: new Map(), backlinks: new Map(), endpointViolations: [] }; }

Given('a graph fixture with an AC that has no own tested-by scenario', function (this: ReadinessWorld) { const f = fr('fixture:FR-1'); const a = ac('fixture:AC-1.1', f.id); this.graph = graph([f, a], [{ from: f.id, to: a.id, type: 'covers' }]); });
Given('an AC with own scenarios but no current passing verifies edge', function (this: ReadinessWorld) { const f = fr('fixture:FR-1'); const a = ac('fixture:AC-1.1', f.id); const s = scen('fixture:SCEN-ac', ['@AC-1.1'], 'FAILED'); this.graph = graph([f, a, s], [{ from: f.id, to: a.id, type: 'covers' }, { from: a.id, to: s.id, type: 'tested-by' }, { from: s.id, to: a.id, type: 'verifies' }, { from: s.id, to: `RESULT-${s.id}-FAILED`, type: 'last-result' }]); });
Given('two sibling ACs whose parent FR has a passing scenario', function (this: ReadinessWorld) { const f = fr('fixture:FR-1'); const a1 = ac('fixture:AC-1.1', f.id); const a2 = ac('fixture:AC-1.2', f.id); const s = scen('fixture:SCEN-parent', ['@FR-1'], 'PASSED'); this.graph = graph([f, a1, a2, s], [{ from: f.id, to: a1.id, type: 'covers' }, { from: f.id, to: a2.id, type: 'covers' }, { from: f.id, to: s.id, type: 'tested-by' }, { from: s.id, to: f.id, type: 'verifies' }, { from: s.id, to: `RESULT-${s.id}-PASSED`, type: 'last-result' }]); });
Given('only the first AC has its own passing scenario', function (this: ReadinessWorld) { const f = fr('fixture:FR-1'); const a1 = ac('fixture:AC-1.1', f.id); const a2 = ac('fixture:AC-1.2', f.id); const s1 = scen('fixture:SCEN-ac-one', ['@AC-1.1'], 'PASSED'); const parent = scen('fixture:SCEN-parent', ['@FR-1'], 'PASSED'); this.graph = graph([f, a1, a2, s1, parent], [{ from: f.id, to: a1.id, type: 'covers' }, { from: f.id, to: a2.id, type: 'covers' }, { from: a1.id, to: s1.id, type: 'tested-by' }, { from: s1.id, to: a1.id, type: 'verifies' }, { from: s1.id, to: `RESULT-${s1.id}-PASSED`, type: 'last-result' }, { from: f.id, to: parent.id, type: 'tested-by' }, { from: parent.id, to: f.id, type: 'verifies' }, { from: parent.id, to: `RESULT-${parent.id}-PASSED`, type: 'last-result' }]); });
Given('multiple ACs with one satisfied criterion and one open criterion', function (this: ReadinessWorld) { const f = fr('fixture:FR-1'); const a1 = ac('fixture:AC-1.1', f.id); const a2 = ac('fixture:AC-1.2', f.id); const s1 = scen('fixture:SCEN-ac-one', ['@AC-1.1'], 'PASSED'); this.graph = graph([f, a1, a2, s1], [{ from: f.id, to: a1.id, type: 'covers' }, { from: f.id, to: a2.id, type: 'covers' }, { from: a1.id, to: s1.id, type: 'tested-by' }, { from: s1.id, to: a1.id, type: 'verifies' }, { from: s1.id, to: `RESULT-${s1.id}-PASSED`, type: 'last-result' }]); });
Given('sibling AC tags copied across scenarios without distinct behavioral assertions', function (this: ReadinessWorld) { const f = fr('fixture:FR-1'); const a = ac('fixture:AC-1.1', f.id); const nodes = [f, a, ...Array.from({ length: 10 }, (_, i) => scen(`fixture:SCEN-copy-${i}`, ['@AC-1.1'], 'PASSED'))]; const edges: SpecGraph['edges'] = [{ from: f.id, to: a.id, type: 'covers' }]; for (const n of nodes.slice(2)) edges.push({ from: a.id, to: n.id, type: 'tested-by' }, { from: n.id, to: a.id, type: 'verifies' }, { from: n.id, to: `RESULT-${n.id}-PASSED`, type: 'last-result' }); this.graph = graph(nodes, edges); });

When('I evaluate completion evidence conformance', function (this: ReadinessWorld) { this.findings = checkConformance(this.graph!, { readinessOwnership: true }); });
When('I build the readiness inventory', function (this: ReadinessWorld) { this.inventory = buildReadinessInventory(this.graph!, { spec: 'fixture' }); });
When('I evaluate mandatory readiness lanes', function (this: ReadinessWorld) { this.inventory = buildReadinessInventory(this.graph!, { spec: 'fixture' }); });
When('I evaluate tag bulk suspicion', function (this: ReadinessWorld) { this.findings = checkConformance(this.graph!, { readinessOwnership: true }); this.graph!.findings = [...this.findings]; this.inventory = buildReadinessInventory(this.graph!, { spec: 'fixture' }); });

Then('UNCOVERED_AC is reported as an error for that exact criterion', function (this: ReadinessWorld) { assert.ok(this.findings!.some((f) => f.code === 'UNCOVERED_AC' && f.nodeId === 'fixture:AC-1.1' && f.severity === 'error')); });
Then('UNVERIFIED_AC is reported as an error for that exact criterion', function (this: ReadinessWorld) { assert.ok(this.findings!.some((f) => f.code === 'UNVERIFIED_AC' && f.nodeId === 'fixture:AC-1.1' && f.severity === 'error')); });
Then('the first AC is satisfied and the second has inherited non-completing context', function (this: ReadinessWorld) { assert.deepEqual(this.inventory!.acs.map((a) => [a.id, a.scenario_ids.length]), [['AC-1.1', 1], ['AC-1.2', 0]]); assert.equal(this.inventory!.ac_satisfaction.satisfied, 1); assert.equal(this.inventory!.ac_satisfaction.status, 'RED'); });
Then('AC_SATISFACTION is RED until every criterion has own passing evidence', function (this: ReadinessWorld) { const readiness = evaluateReadiness({ inventory: this.inventory!, lanes: {} }); assert.equal(this.inventory!.ac_satisfaction.status, 'RED'); assert.equal(readiness.lanes.AC_SATISFACTION.blocking, true); assert.equal(readiness.overall, 'NOT_READY'); });
Then('blocking TAG_BULK_SUSPECT is emitted and copied tags are not counted as proof', function (this: ReadinessWorld) { const finding = this.findings!.find((f) => f.code === 'TAG_BULK_SUSPECT'); assert.ok(finding); assert.equal(finding!.severity, 'info'); assert.equal(this.inventory!.ac_satisfaction.status, 'RED'); });
