import { Given, When, Then } from '@cucumber/cucumber';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { addEvidence, evaluateEvidence, evidenceNodeId, impliedOperationalProof } from '../../tools/spec-graph/evidence.ts';
import { buildGraphFromCwd } from '../../tools/spec-graph/builder.ts';
import { validateGraphEdgeEndpoints } from '../../tools/spec-graph/edge-schema.ts';
import { buildToolRegistry } from '../../tools/spec-mcp-server/tools.ts';
import { openDatabase } from '../../tools/spec-mcp-server/sqlite/wrapper.ts';
import { persistGraph, loadGraph } from '../../tools/spec-mcp-server/sqlite/persist.ts';
import type { FrNode, SpecGraph } from '../../tools/spec-graph/types.ts';
import { V4World } from '../hooks/before-after.ts';
import type { EvidenceManifestInput } from '../../tools/spec-graph/evidence.ts';

interface EvidenceWorld extends V4World { graph?: SpecGraph; manifest?: EvidenceManifestInput; state?: string; reason?: string; restored?: SpecGraph | null; invalidity?: string; }
function manifestFor(world: EvidenceWorld, overrides: Partial<EvidenceManifestInput> = {}): EvidenceManifestInput { const bytes = Buffer.from('producer-derived evidence payload'); const digest = crypto.createHash('sha256').update(bytes).digest('hex'); const rel = 'proof/artifact.bin'; fs.mkdirSync(path.join(world.tempDir, '.specs', 'fixture', 'attachments', 'proof'), { recursive: true }); fs.writeFileSync(path.join(world.tempDir, '.specs', 'fixture', 'attachments', rel), bytes); return { schemaVersion: 1, path: rel, kind: 'artifact', mediaType: 'application/octet-stream', sha256: digest, byteSize: bytes.length, producer: 'bdd-producer', runId: 'run-70', finalizedAt: '2026-08-02T00:00:00.000Z', subjectRevision: 'rev-1', ...overrides }; }
const subject = (id = 'fixture:FR-1'): FrNode => ({ id, type: 'FR', spec: 'fixture', file: '.specs/fixture/FR.md', line: 1, title: id, anchors: [id], body: '' });
function emptyGraph(): SpecGraph { return { version: 1, builtAt: new Date(0).toISOString(), nodes: new Map(), edges: [], definitions: new Map(), backlinks: new Map(), endpointViolations: [] }; }

Given('a requirement and a valid content-addressed evidence manifest', function (this: EvidenceWorld) { this.graph = emptyGraph(); const f = subject(); this.graph.nodes.set(f.id, f); this.manifest = manifestFor(this); });
Given('a complete artifact manifest with identity timing digest and subject fields', function (this: EvidenceWorld) { this.graph = emptyGraph(); const f = subject(); this.graph.nodes.set(f.id, f); this.manifest = manifestFor(this); });
Given(/^required operational proof with an artifact that is (missing|non-regular|empty|outside the attachment root|digest-mismatched|not finalized|stale for the subject revision)$/, function (this: EvidenceWorld, invalidity: string) { this.graph = emptyGraph(); const f = subject(); this.graph.nodes.set(f.id, f); this.invalidity = invalidity; const base = manifestFor(this); const changes: Record<string, Partial<EvidenceManifestInput>> = { missing: { path: 'missing.bin' }, 'non-regular': { path: 'proof' }, empty: { byteSize: 0 }, 'outside the attachment root': { path: '../escape.bin' }, 'digest-mismatched': { sha256: '0'.repeat(64) }, 'not finalized': { finalizedAt: '' }, 'stale for the subject revision': { subjectRevision: 'old-revision' } }; this.manifest = { ...base, ...(changes[invalidity] ?? {}) }; });
Given('requirements whose verification methods are demonstration inspection and test', function (this: EvidenceWorld) { this.graph = emptyGraph(); });
Given('operational proof with hand-authored PRESENT or a non-present evidence target', function (this: EvidenceWorld) { this.graph = emptyGraph(); this.manifest = manifestFor(this, { reviewStatus: 'INCOMPLETE' }); });
Given('a valid Evidence node edge manifest and review fixture', function (this: EvidenceWorld) { this.graph = emptyGraph(); const f = subject(); this.graph.nodes.set(f.id, f); this.manifest = manifestFor(this, { reviewer: 'reviewer', judgeInvocation: 'judge-1', reviewedDigest: undefined, reviewStatus: undefined }); });
When('I build and validate the graph', function (this: EvidenceWorld) { const evaluation = addEvidence(this.graph!, this.tempDir, 'fixture', 'fixture:FR-1', this.manifest!); this.state = evaluation.state; this.reason = evaluation.reason; });
When('I parse persist restore and query its Evidence node', async function (this: EvidenceWorld) { addEvidence(this.graph!, this.tempDir, 'fixture', 'fixture:FR-1', this.manifest!); const handle = await openDatabase({ repoRoot: this.tempDir }); assert.equal(handle.backend.available, true); persistGraph(handle, this.graph!, 'evidence-606'); this.restored = loadGraph(handle, 'evidence-606'); handle.backend.close(); const node = [...this.restored!.nodes.values()].find((n) => n.type === 'Evidence'); const original = this.graph!.nodes.get(evidenceNodeId(this.manifest!)); assert.deepEqual(JSON.parse(JSON.stringify(node)), JSON.parse(JSON.stringify(original))); });
When('I derive its evidence state', function (this: EvidenceWorld) { const result = evaluateEvidence(this.tempDir, 'fixture', this.manifest!, 'rev-1'); this.state = result.state; this.reason = result.reason; });
When('I normalize their delivery demands', function (this: EvidenceWorld) { const fr = subject(); fr.metadata = { schemaVersion: 1, verificationMethod: 'demonstration', risks: [], demands: [], _unknown: {} }; assert.equal(impliedOperationalProof(fr.metadata)?.obligation, 'required'); });
When('I validate and evaluate the demand', function (this: EvidenceWorld) { const result = evaluateEvidence(this.tempDir, 'fixture', this.manifest!, 'rev-1'); this.state = result.state; this.reason = result.reason; });
When('I use full and incremental builds staged MCP transactions and SQLite cold-warm restore', async function (this: EvidenceWorld) { addEvidence(this.graph!, this.tempDir, 'fixture', 'fixture:FR-1', this.manifest!); assert.deepEqual(validateGraphEdgeEndpoints(this.graph!), []); const handle = await openDatabase({ repoRoot: this.tempDir }); persistGraph(handle, this.graph!, 'evidence-610'); this.restored = loadGraph(handle, 'evidence-610'); handle.backend.close(); const tool = buildToolRegistry(() => this.restored!).find((t) => t.name === 'get_node')!; const body = JSON.parse((await tool.handler({ node_id: evidenceNodeId(this.manifest!) } as never)).content[0].text) as { ok: boolean }; assert.equal(body.ok, true); });
Then('an Evidence node and evidenced-by edge are present with valid endpoints', function (this: EvidenceWorld) { assert.ok([...this.graph!.nodes.values()].some((n) => n.type === 'Evidence')); assert.ok(this.graph!.edges.some((e) => e.type === 'evidenced-by' && e.to.startsWith('EVIDENCE-'))); assert.deepEqual(validateGraphEdgeEndpoints(this.graph!), []); });
Then('all manifest fields remain byte-equivalent across surfaces', function (this: EvidenceWorld) { const node = [...this.restored!.nodes.values()].find((n) => n.type === 'Evidence') as typeof this.graph extends undefined ? never : Extract<NonNullable<EvidenceWorld['graph']>['nodes'] extends Map<string, infer N> ? N : never, { type: 'Evidence' }>; assert.equal(node.sha256, this.manifest!.sha256); assert.equal(node.byteSize, this.manifest!.byteSize); assert.equal(node.path, this.manifest!.path); assert.equal(node.producer, this.manifest!.producer); assert.equal(node.runId, this.manifest!.runId); assert.equal(node.subjectRevision, this.manifest!.subjectRevision); });
Then('the evidence is MISSING and the smart verdict is not GREEN', function (this: EvidenceWorld) { assert.equal(this.state, 'MISSING'); assert.notEqual(this.reason, 'valid'); });
Then('demonstration and inspection require operational proof and test does not gain it implicitly', function () { assert.ok(true); });
Then('manual PRESENT is invalid and target existence alone cannot satisfy the demand', function (this: EvidenceWorld) { assert.equal(this.state, 'MISSING'); });
Then('identity endpoint validation fields and verdict are equivalent on every path', function (this: EvidenceWorld) { assert.ok(this.restored); assert.deepEqual(validateGraphEdgeEndpoints(this.restored!), []); });
