Feature: codex-cli-support

  # Generated by `scenario-writer` resolver from `FR.md`. Each scenario is a skeleton — test authors MUST fill in real step implementations.

  Background:
    # Define preconditions and test setup here

  @feature1
  Scenario: FR-1 — First-Class Codex Platform @feature1
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature2
  Scenario: FR-2 — Trusted Project-Local Artifact Model @feature2
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature3
  Scenario: FR-3 — Existing Project Artifact Protection @feature3
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature4
  Scenario: FR-4 — Version-Aware Codex Hook Capability Model @feature4
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature5
  Scenario: FR-5 — Hook Orchestration and Conflict Discipline @feature5
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature6
  Scenario: FR-6 — AGENTS-First Guidance and CLAUDE Coexistence @feature6
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature7
  Scenario: FR-7 — Codex Skills Packaging with Layered Discovery @feature7
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature8
  Scenario: FR-8 — Project-Level Codex MCP Configuration @feature8
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature9
  Scenario: FR-9 — Extension Parity Support Matrix @feature9
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature10
  Scenario: FR-10 — Windows Execution Strategy for Codex @feature10
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature11
  Scenario: FR-11 — Managed Update and Reinstall Path @feature11
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature12
  Scenario: FR-12 — Explicit Codex Parity Routing @feature12
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.
