# Configuration for forbid-root-artifacts
# See: https://github.com/user/dev-pomogator

mode: extend
allow:
- .env.test
- CHANGELOG.md
- docker-compose.test.yml
- Dockerfile.test
- install.ps1
- install.sh
- vitest.config.ts
