services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: dev-pomogator-test:local
    env_file:
      - .env.test
    environment:
      - HOME=/home/testuser
      - DEV_POMOGATOR_TEST_IN_DOCKER=1
