import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'fs-extra';
import path from 'path';
import {
  appPath,
  runInstaller,
  runCheckUpdate,
  setupCleanState,
  getDevPomogatorConfig,
  saveDevPomogatorConfig,
  hoursAgo,
  type InstallerResult,
} from './helpers';

/**
 * CORE019: Extension Beta Flag
 *
 * Integration tests for the beta-flag feature (.specs/extension-beta-flag/).
 * These tests call the real installer/updater binaries and verify behavior in
 * the dev-pomogator config and the regenerated `plugin.json` — not by
 * inspecting source strings or simulating logic.
 *
 * Beta marker is set on `extensions/docker-optimization/extension.json`
 * (`stability: "beta"`). The "installed / not installed" proof comes from:
 *   1. `~/.dev-pomogator/config.json` → `installedExtensions[]`
 *   2. `<project>/.dev-pomogator/.claude-plugin/plugin.json` (description +
 *      skills[]) — regenerated by the installer on every run, so it reflects
 *      the actual install state even in this dogfooding repo where the source
 *      `.claude/skills/docker-optimize/SKILL.md` lives in the same tree as the
 *      installed copy.
 */

const BETA_EXT = 'docker-optimization';
const BETA_SKILL_NAME = 'docker-optimize';
const PLUGIN_JSON_REL = path.join('.dev-pomogator', '.claude-plugin', 'plugin.json');

interface PluginJson {
  description?: string;
  skills?: Array<{ name: string; path: string }>;
}

async function readPluginJson(): Promise<PluginJson> {
  return fs.readJson(appPath(PLUGIN_JSON_REL));
}

describe('CORE019: Extension Beta Flag', () => {
  // ===========================================================================
  // FR-1: stability field parsing
  // ===========================================================================

  // @feature1
  it('CORE019_01: extension with stability beta is parsed correctly', async () => {
    const manifestPath = appPath('extensions', BETA_EXT, 'extension.json');
    const manifest = await fs.readJson(manifestPath);
    expect(manifest.stability).toBe('beta');
  });

  // @feature1
  it('CORE019_02: extension without stability field defaults to stable', async () => {
    const manifestPath = appPath('extensions', 'auto-commit', 'extension.json');
    const manifest = await fs.readJson(manifestPath);
    expect(manifest.stability).toBeUndefined();
  });

  // @feature1
  it('CORE019_08: isBeta helper works correctly', async () => {
    const { isBeta } = await import(
      appPath('dist', 'installer', 'extensions.js')
    );
    expect(isBeta({ stability: 'beta' })).toBe(true);
    expect(isBeta({ stability: 'stable' })).toBe(false);
    expect(isBeta({})).toBe(false);
    expect(isBeta({ stability: undefined })).toBe(false);
  });

  // ===========================================================================
  // FR-2 / FR-3: buildExtensionChoices helper (single source of truth for both
  // interactive installer paths). Calling it directly verifies the actual
  // production logic — not a string match against source code.
  // ===========================================================================

  // @feature2
  it('CORE019_03: buildExtensionChoices labels beta with "(BETA)"', async () => {
    const { listExtensions, buildExtensionChoices } = await import(
      appPath('dist', 'installer', 'extensions.js')
    );

    const extensions = await listExtensions();
    const choices = buildExtensionChoices(extensions);

    const betaChoice = choices.find((c: { value: string }) => c.value === BETA_EXT);
    expect(betaChoice, `${BETA_EXT} must appear in choices`).toBeDefined();
    expect(betaChoice!.name).toContain('(BETA)');

    // Every stable extension must NOT carry the (BETA) label.
    const stableChoices = choices.filter((c: { value: string }) => c.value !== BETA_EXT);
    for (const stable of stableChoices) {
      expect(stable.name, `${stable.value} must not be labeled (BETA)`).not.toContain('(BETA)');
    }
  });

  // @feature2
  it('CORE019_04: buildExtensionChoices unchecks beta by default', async () => {
    const { listExtensions, buildExtensionChoices } = await import(
      appPath('dist', 'installer', 'extensions.js')
    );

    const extensions = await listExtensions();
    const choices = buildExtensionChoices(extensions);

    const betaChoice = choices.find((c: { value: string }) => c.value === BETA_EXT);
    expect(betaChoice!.checked).toBe(false);

    const stableChoices = choices.filter((c: { value: string }) => c.value !== BETA_EXT);
    expect(stableChoices.length).toBeGreaterThan(0);
    for (const stable of stableChoices) {
      expect(stable.checked, `${stable.value} must be checked by default`).toBe(true);
    }
  });

  // ===========================================================================
  // FR-4: --all excludes beta — REAL installer run + filesystem assertion
  // FR-6: updater does not auto-add new beta — runs updater on the same state
  //       and asserts beta still absent.
  // ===========================================================================
  describe('FR-4 + FR-6: --all excludes beta and updater leaves it absent', () => {
    let installResult: InstallerResult;

    beforeAll(async () => {
      await setupCleanState('claude');
      installResult = await runInstaller('--claude --all');
      if (installResult.exitCode !== 0) {
        throw new Error(`Installer failed: ${installResult.logs}`);
      }
    });

    // @feature3
    it('CORE019_05: --all excludes beta extensions (config + plugin.json + logs)', async () => {
      // Config: docker-optimization absent, stable extensions present
      const config = await getDevPomogatorConfig();
      expect(config).not.toBeNull();
      const installedNames = config!.installedExtensions
        .filter(ext => ext.platform === 'claude')
        .map(ext => ext.name);
      expect(installedNames).not.toContain(BETA_EXT);
      expect(installedNames).toContain('auto-commit');

      // plugin.json (regenerated by installer): docker-optimization absent
      // from both the description and the registered skills list.
      const plugin = await readPluginJson();
      expect(plugin.description ?? '').not.toContain(BETA_EXT);
      const skillNames = (plugin.skills ?? []).map(s => s.name);
      expect(skillNames).not.toContain(BETA_SKILL_NAME);

      // Logs: installer announced the skip with the beta extension name
      expect(installResult.logs).toMatch(/Skipping beta plugins:[^\n]*docker-optimization/);
    });

    // @feature3 — FR-6: updater iterates installedExtensions only, so a beta
    // extension that was never installed must remain absent after the updater
    // runs (even when the updater is forced to do work).
    it('CORE019_07: updater does NOT add new beta after --all install', async () => {
      // Force the updater to actually run by bypassing cooldown and pretending
      // one already-installed extension is out of date. We do NOT use
      // setupNeedsUpdateState because it overwrites the entire config — we want
      // the post-install state preserved so this asserts the real "updater run
      // over realistic config" path.
      const config = await getDevPomogatorConfig();
      expect(config).not.toBeNull();
      config!.lastCheck = hoursAgo(25);
      const target = config!.installedExtensions.find(
        ext => ext.platform === 'claude' && ext.name === 'auto-commit'
      );
      expect(target, 'auto-commit must be installed for this test to be meaningful').toBeDefined();
      target!.version = '0.0.1';
      await saveDevPomogatorConfig(config!);

      await runCheckUpdate('--claude');

      const after = await getDevPomogatorConfig();
      const afterNames = after!.installedExtensions
        .filter(ext => ext.platform === 'claude')
        .map(ext => ext.name);
      expect(afterNames).not.toContain(BETA_EXT);

      // plugin.json regenerated by updater (FR-14) — docker-optimization
      // must still be absent from both description and registered skills.
      const plugin = await readPluginJson();
      expect(plugin.description ?? '').not.toContain(BETA_EXT);
      const skillNames = (plugin.skills ?? []).map(s => s.name);
      expect(skillNames).not.toContain(BETA_SKILL_NAME);
    });
  });

  // ===========================================================================
  // FR-5: --all --include-beta installs beta — REAL installer run
  // ===========================================================================
  describe('FR-5: --all --include-beta installs beta', () => {
    let installResult: InstallerResult;

    beforeAll(async () => {
      await setupCleanState('claude');
      installResult = await runInstaller('--claude --all --include-beta');
      if (installResult.exitCode !== 0) {
        throw new Error(`Installer failed: ${installResult.logs}`);
      }
    });

    // @feature4
    it('CORE019_06: --all --include-beta installs everything (config + plugin.json + logs)', async () => {
      // Config: docker-optimization present alongside stable extensions
      const config = await getDevPomogatorConfig();
      expect(config).not.toBeNull();
      const installedNames = config!.installedExtensions
        .filter(ext => ext.platform === 'claude')
        .map(ext => ext.name);
      expect(installedNames).toContain(BETA_EXT);
      expect(installedNames).toContain('auto-commit');

      // plugin.json: docker-optimization listed in description AND its skill
      // is registered in skills[]. This is the proof the installer actually
      // wired the extension into the project, not just appended a config row.
      const plugin = await readPluginJson();
      expect(plugin.description ?? '').toContain(BETA_EXT);
      const skillNames = (plugin.skills ?? []).map(s => s.name);
      expect(skillNames).toContain(BETA_SKILL_NAME);

      // Logs: no skip-beta message
      expect(installResult.logs).not.toMatch(/Skipping beta plugins/);
    });
  });
});
