<#
.SYNOPSIS
    DevContainer Worktree Manager
    Создание, управление и мерж параллельных девконтейнеров через git worktrees.

.DESCRIPTION
    Каждый worktree получает свой набор портов (noVNC, VNC) через .devcontainer/.env.
    VS Code при "Reopen in Container" создаёт отдельный Docker Compose project → volumes изолированы.

.PARAMETER New
    Имя ветки для нового worktree. Создаёт worktree + .env + открывает VS Code.

.PARAMETER Open
    Имя существующего worktree для открытия в VS Code.

.PARAMETER Remove
    Имя worktree для удаления.

.PARAMETER Merge
    Имя worktree/ветки для мержа в main. Полный анализ + dry-run + мерж + отчёт.

.PARAMETER Status
    Показать конфликт-матрицу: какие worktrees конфликтуют друг с другом и с main.

.PARAMETER Squash
    Использовать squash merge вместо обычного (с -Merge).

.PARAMETER Rebuild
    Имя worktree для пересборки девконтейнера (docker compose build + up).

.PARAMETER Health
    Имя worktree для проверки healthcheck статуса.

.EXAMPLE
    .\scripts\launch-worktree.ps1                          # Интерактивное меню
    .\scripts\launch-worktree.ps1 -New feature/my-branch   # Создать и открыть
    .\scripts\launch-worktree.ps1 -Merge feature-branch    # Анализ + мерж в main
    .\scripts\launch-worktree.ps1 -Merge feature-branch -Squash  # Squash мерж
    .\scripts\launch-worktree.ps1 -Status                  # Конфликт-матрица всех worktrees
    .\scripts\launch-worktree.ps1 -Rebuild feature-branch  # Пересобрать девконтейнер
    .\scripts\launch-worktree.ps1 -Health feature-branch   # Проверить healthcheck
#>

param(
    [string]$New,
    [string]$Open,
    [string]$Remove,
    [string]$Merge,
    [switch]$Status,
    [switch]$Squash,
    [string]$Rebuild,
    [string]$Health
)

$ErrorActionPreference = "Continue"

# --- Config ---
$MainRepoRoot = git rev-parse --show-toplevel 2>$null
if (-not $MainRepoRoot) {
    $MainRepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
}
$MainRepoRoot = (Resolve-Path $MainRepoRoot).Path

$WorktreeBaseDir = Split-Path -Parent $MainRepoRoot
$RepoName = Split-Path -Leaf $MainRepoRoot

$BaseNoVncPort = 6080
$BaseVncPort = 5900

# --- Helpers ---

function Get-Worktrees {
    $raw = git worktree list --porcelain 2>$null
    $worktrees = @()
    $current = @{}

    foreach ($line in $raw) {
        if ($line -match '^worktree (.+)$') {
            if ($current.Count -gt 0) { $worktrees += [PSCustomObject]$current }
            $current = @{ Path = $Matches[1]; Branch = ""; Bare = $false }
        }
        elseif ($line -match '^branch refs/heads/(.+)$') {
            $current.Branch = $Matches[1]
        }
        elseif ($line -match '^bare$') {
            $current.Bare = $true
        }
    }
    if ($current.Count -gt 0) { $worktrees += [PSCustomObject]$current }

    # Filter out main worktree (same as repo root)
    $mainNorm = $MainRepoRoot.Replace('\', '/').TrimEnd('/')
    $worktrees | Where-Object {
        $pathNorm = $_.Path.Replace('\', '/').TrimEnd('/')
        $pathNorm -ne $mainNorm
    }
}

function Get-WorktreeEnvPort {
    param([string]$WorktreePath)
    $envFile = Join-Path (Join-Path $WorktreePath ".devcontainer") ".env"
    if (Test-Path $envFile) {
        $content = Get-Content $envFile -Raw
        if ($content -match 'HOST_NOVNC_PORT=(\d+)') {
            return [int]$Matches[1]
        }
    }
    return $null
}

function Find-WorktreeByName {
    param([string]$Name, [array]$Worktrees)
    $Worktrees | Where-Object {
        $leaf = Split-Path -Leaf $_.Path
        $leaf -eq $Name -or $leaf -eq "$RepoName-$Name" -or $_.Branch -eq $Name
    } | Select-Object -First 1
}

function Get-NextPorts {
    param([array]$Worktrees)
    $usedPorts = @($BaseNoVncPort)

    if (-not $Worktrees) { $Worktrees = @(Get-Worktrees) }
    foreach ($wt in $Worktrees) {
        $port = Get-WorktreeEnvPort $wt.Path
        if ($port) { $usedPorts += $port }
    }

    $maxNoVnc = ($usedPorts | Measure-Object -Maximum).Maximum
    $nextNoVnc = $maxNoVnc + 1
    $nextVnc = $BaseVncPort + ($nextNoVnc - $BaseNoVncPort)

    return @{ NoVnc = $nextNoVnc; Vnc = $nextVnc }
}

function Get-WorktreeDirName {
    param([string]$BranchName)
    $safeName = $BranchName -replace '[/\\]', '-'
    return "$RepoName-$safeName"
}

function New-WorktreeEnv {
    param([string]$WorktreePath, [int]$NoVncPort, [int]$VncPort)
    $envDir = Join-Path $WorktreePath ".devcontainer"
    if (-not (Test-Path $envDir)) {
        New-Item -ItemType Directory -Path $envDir -Force | Out-Null
    }
    $envFile = Join-Path $envDir ".env"
    # Resolve host repos path (parent of main repo)
    $reposPath = (Split-Path -Parent $MainRepoRoot).Replace('\', '\\')
    @"
# Auto-generated by launch-worktree.ps1
HOST_NOVNC_PORT=$NoVncPort
HOST_VNC_PORT=$VncPort
HOST_REPOS_PATH=$reposPath
"@ | Set-Content -Path $envFile -Encoding UTF8 -NoNewline
}

function Get-WorktreeHealthStatus {
    param([string]$WorktreePath)
    # Derive compose project name from worktree directory
    $leaf = (Split-Path -Leaf $WorktreePath).ToLower() -replace '[^a-z0-9]', ''
    $containers = docker ps -a --filter "label=com.docker.compose.project=$leaf" --format "{{.ID}}" 2>$null
    if ([string]::IsNullOrEmpty($containers)) {
        # Try matching by port from .env
        $port = Get-WorktreeEnvPort $WorktreePath
        if ($port) {
            $containers = docker ps -a --filter "publish=$port" --format "{{.ID}}" 2>$null
        }
    }
    if ([string]::IsNullOrEmpty($containers)) { return "not running" }
    $health = docker inspect --format='{{.State.Health.Status}}' $containers 2>$null
    if ($health) { return $health }
    $state = docker inspect --format='{{.State.Status}}' $containers 2>$null
    if ($state) { return $state }
    return "unknown"
}

function Invoke-RebuildWorktree {
    param([string]$Name)
    $worktrees = @(Get-Worktrees)
    $match = Find-WorktreeByName -Name $Name -Worktrees $worktrees
    if (-not $match) {
        Write-Host "Worktree not found: $Name" -ForegroundColor Red
        return
    }
    $composePath = Join-Path $match.Path ".devcontainer/docker-compose.yml"
    if (-not (Test-Path $composePath)) {
        Write-Host "No docker-compose.yml in worktree: $($match.Path)" -ForegroundColor Red
        return
    }
    Write-Host "Rebuilding devcontainer for: $($match.Branch)" -ForegroundColor Cyan
    Push-Location (Join-Path $match.Path ".devcontainer")
    docker compose build
    docker compose up -d
    Pop-Location
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Rebuild complete." -ForegroundColor Green
    } else {
        Write-Host "Rebuild failed." -ForegroundColor Red
    }
}

function Show-WorktreeHealth {
    param([string]$Name)
    $worktrees = @(Get-Worktrees)
    $match = Find-WorktreeByName -Name $Name -Worktrees $worktrees
    if (-not $match) {
        Write-Host "Worktree not found: $Name" -ForegroundColor Red
        return
    }
    $status = Get-WorktreeHealthStatus $match.Path
    $color = switch ($status) {
        "healthy"     { "Green" }
        "unhealthy"   { "Red" }
        "starting"    { "Yellow" }
        "not running" { "Gray" }
        default       { "White" }
    }
    Write-Host "$($match.Branch): " -NoNewline
    Write-Host $status -ForegroundColor $color
}

function New-Worktree {
    param([string]$BranchName)

    $dirName = Get-WorktreeDirName $BranchName
    $wtPath = Join-Path $WorktreeBaseDir $dirName

    if (Test-Path $wtPath) {
        Write-Host "Worktree already exists: $wtPath" -ForegroundColor Yellow
        # Ensure .env exists
        $envFile = Join-Path (Join-Path $wtPath ".devcontainer") ".env"
        if (-not (Test-Path $envFile)) {
            $ports = Get-NextPorts
            New-WorktreeEnv -WorktreePath $wtPath -NoVncPort $ports.NoVnc -VncPort $ports.Vnc
            Write-Host "  Created .env: noVNC=$($ports.NoVnc), VNC=$($ports.Vnc)" -ForegroundColor Green
        }
        Open-Worktree -WorktreePath $wtPath
        return
    }

    # Check if branch exists
    $branchExists = $false
    $null = git rev-parse --verify "refs/heads/$BranchName" 2>&1
    if ($LASTEXITCODE -eq 0) { $branchExists = $true }

    if ($branchExists) {
        Write-Host "Creating worktree for existing branch '$BranchName'..."
        git worktree add $wtPath $BranchName 2>&1
    }
    else {
        Write-Host "Creating worktree with new branch '$BranchName'..."
        git worktree add -b $BranchName $wtPath 2>&1
    }

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to create worktree" -ForegroundColor Red
        return
    }

    # Assign ports
    $ports = Get-NextPorts
    New-WorktreeEnv -WorktreePath $wtPath -NoVncPort $ports.NoVnc -VncPort $ports.Vnc

    Write-Host ""
    Write-Host "Worktree created: $wtPath" -ForegroundColor Green
    Write-Host "  Branch: $BranchName"
    Write-Host "  noVNC:  localhost:$($ports.NoVnc)"
    Write-Host "  VNC:    localhost:$($ports.Vnc)"
    Write-Host ""

    Open-Worktree -WorktreePath $wtPath
}

function Open-Worktree {
    param([string]$WorktreePath)
    Write-Host "Opening VS Code: $WorktreePath" -ForegroundColor Cyan
    Write-Host "  -> Use 'Reopen in Container' to start the devcontainer"
    code $WorktreePath
}

function Remove-Worktree {
    param([string]$Name)

    $worktrees = @(Get-Worktrees)
    $match = Find-WorktreeByName -Name $Name -Worktrees $worktrees

    if (-not $match) {
        Write-Host "Worktree not found: $Name" -ForegroundColor Red
        Write-Host "Available worktrees:"
        foreach ($wt in $worktrees) {
            Write-Host "  $(Split-Path -Leaf $wt.Path)  ($($wt.Branch))"
        }
        return
    }

    $wtPath = $match.Path
    $branch = $match.Branch

    Write-Host "Removing worktree: $wtPath (branch: $branch)" -ForegroundColor Yellow
    $confirm = Read-Host "Are you sure? [y/N]"
    if ($confirm -ne 'y' -and $confirm -ne 'Y') {
        Write-Host "Cancelled." -ForegroundColor Gray
        return
    }

    git worktree remove $wtPath --force 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Worktree removed." -ForegroundColor Green
        $deleteBranch = Read-Host "Delete branch '$branch'? [y/N]"
        if ($deleteBranch -eq 'y' -or $deleteBranch -eq 'Y') {
            git branch -d $branch 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Write-Host "Branch not fully merged. Force delete? [y/N]" -ForegroundColor Yellow
                $force = Read-Host
                if ($force -eq 'y' -or $force -eq 'Y') {
                    git branch -D $branch 2>&1
                }
            }
        }
    }
    else {
        Write-Host "Failed to remove worktree" -ForegroundColor Red
    }
}

# --- Merge & Status ---

function Get-MainBranch {
    # Detect main branch name
    foreach ($candidate in @("main", "master")) {
        $null = git rev-parse --verify "refs/heads/$candidate" 2>&1
        if ($LASTEXITCODE -eq 0) { return $candidate }
    }
    return "master"
}

function Test-MergeTree {
    # Zero-touch conflict detection via git merge-tree (Git 2.38+)
    # Returns: hashtable with .Clean (bool), .ConflictFiles (array), .Output (string)
    param([string]$Base, [string]$Branch)
    $output = git merge-tree --write-tree --no-messages $Base $Branch 2>&1
    $exitCode = $LASTEXITCODE
    $conflicts = @()
    if ($exitCode -ne 0) {
        # Parse conflicting files from merge-tree output
        $infoOutput = git merge-tree --write-tree $Base $Branch 2>&1
        foreach ($line in $infoOutput) {
            if ($line -match '^CONFLICT \(([^)]+)\): (.+)$') {
                $conflicts += [PSCustomObject]@{
                    Type = $Matches[1]
                    File = $Matches[2].Trim()
                }
            }
        }
    }
    return @{ Clean = ($exitCode -eq 0); ConflictFiles = $conflicts; Output = ($output -join "`n") }
}

function Get-BranchDivergence {
    param([string]$Base, [string]$Branch)
    $ahead = git rev-list --count "$Base..$Branch" 2>&1
    $behind = git rev-list --count "$Branch..$Base" 2>&1
    $mergeBase = git merge-base $Base $Branch 2>&1
    $filesChanged = git diff --stat "$Base...$Branch" 2>&1
    $diffNumstat = git diff --numstat "$Base...$Branch" 2>&1
    $additions = 0; $deletions = 0; $fileCount = 0
    foreach ($line in $diffNumstat) {
        if ($line -match '^(\d+)\s+(\d+)\s+(.+)$') {
            $additions += [int]$Matches[1]
            $deletions += [int]$Matches[2]
            $fileCount++
        }
    }
    return @{
        Ahead = [int]$ahead
        Behind = [int]$behind
        MergeBase = "$mergeBase"
        FilesChanged = $fileCount
        Additions = $additions
        Deletions = $deletions
        FileStat = ($filesChanged -join "`n")
    }
}

function Test-SensitiveContent {
    # Scan diff for secrets/sensitive data
    param([string]$Base, [string]$Branch)
    $patterns = @(
        'password\s*[:=]'
        'secret\s*[:=]'
        'api[_-]?key\s*[:=]'
        'token\s*[:=]'
        'private[_-]?key'
        'BEGIN (RSA |EC |DSA )?PRIVATE KEY'
        'AKIA[0-9A-Z]{16}'  # AWS access key
    )
    $findings = @()
    $diff = git diff "$Base...$Branch" 2>&1
    $currentFile = ""
    $lineNum = 0
    foreach ($line in $diff) {
        if ($line -match '^\+\+\+ b/(.+)$') {
            $currentFile = $Matches[1]
            $lineNum = 0
        }
        elseif ($line -match '^\+' -and $line -notmatch '^\+\+\+') {
            $lineNum++
            foreach ($pat in $patterns) {
                if ($line -imatch $pat) {
                    $findings += [PSCustomObject]@{
                        File = $currentFile
                        Pattern = $pat
                        Line = $line.Substring(1).Trim()
                    }
                    break
                }
            }
        }
    }
    return $findings
}

function Invoke-MergeWorktree {
    param([string]$Name, [switch]$UseSquash)

    $mainBranch = Get-MainBranch
    $worktrees = @(Get-Worktrees)
    $match = Find-WorktreeByName -Name $Name -Worktrees $worktrees

    # Resolve branch name (works with both worktree name and bare branch name)
    $branch = $null
    if ($match) {
        $branch = $match.Branch
    }
    else {
        # Maybe it's a branch name without a worktree
        $null = git rev-parse --verify "refs/heads/$Name" 2>&1
        if ($LASTEXITCODE -eq 0) { $branch = $Name }
    }

    if (-not $branch) {
        Write-Host "Branch or worktree not found: $Name" -ForegroundColor Red
        return
    }

    Write-Host ""
    Write-Host "=== MERGE ANALYSIS: $branch -> $mainBranch ===" -ForegroundColor Cyan
    Write-Host ""

    # --- Phase 1: Pre-flight checks ---
    Write-Host "[1/6] Pre-flight checks..." -ForegroundColor White

    # Check for uncommitted changes on main
    $mainDirty = git diff --quiet HEAD 2>&1
    $mainUntrackedCount = (git ls-files --others --exclude-standard 2>&1 | Measure-Object -Line).Lines
    if ($LASTEXITCODE -ne 0 -or $mainUntrackedCount -gt 0) {
        Write-Host "  WARNING: main has uncommitted changes" -ForegroundColor Yellow
    }
    else {
        Write-Host "  main working tree: clean" -ForegroundColor Green
    }

    # Fetch latest
    Write-Host "  Fetching latest..." -ForegroundColor Gray
    git fetch origin 2>&1 | Out-Null

    # Check if branch is up-to-date with remote
    $localSha = git rev-parse $branch 2>&1
    $remoteSha = git rev-parse "origin/$branch" 2>&1
    if ($LASTEXITCODE -eq 0 -and $localSha -ne $remoteSha) {
        Write-Host "  WARNING: local '$branch' differs from remote" -ForegroundColor Yellow
    }

    Write-Host "  Pre-flight: OK" -ForegroundColor Green
    Write-Host ""

    # --- Phase 2: Divergence analysis ---
    Write-Host "[2/6] Divergence analysis..." -ForegroundColor White
    $div = Get-BranchDivergence -Base $mainBranch -Branch $branch

    Write-Host "  Commits ahead of $mainBranch  : " -NoNewline
    Write-Host "$($div.Ahead)" -ForegroundColor Yellow
    Write-Host "  Commits behind $mainBranch : " -NoNewline
    if ($div.Behind -gt 0) {
        Write-Host "$($div.Behind)" -ForegroundColor Red
    }
    else {
        Write-Host "$($div.Behind)" -ForegroundColor Green
    }
    Write-Host "  Files changed: $($div.FilesChanged) (+$($div.Additions) -$($div.Deletions))"

    if ($div.Behind -gt 10) {
        Write-Host ""
        Write-Host "  ATTENTION: Branch is $($div.Behind) commits behind $mainBranch." -ForegroundColor Red
        Write-Host "  Consider rebasing first: git rebase $mainBranch" -ForegroundColor Yellow
    }
    Write-Host ""

    # --- Phase 3: Conflict detection (dry-run) ---
    Write-Host "[3/6] Conflict detection (git merge-tree)..." -ForegroundColor White
    $mergeResult = Test-MergeTree -Base $mainBranch -Branch $branch

    if ($mergeResult.Clean) {
        Write-Host "  Result: CLEAN MERGE" -ForegroundColor Green
        Write-Host "  No conflicts detected." -ForegroundColor Green
    }
    else {
        Write-Host "  Result: CONFLICTS DETECTED" -ForegroundColor Red
        Write-Host ""
        foreach ($c in $mergeResult.ConflictFiles) {
            Write-Host "  CONFLICT ($($c.Type)): $($c.File)" -ForegroundColor Red
        }
    }
    Write-Host ""

    # --- Phase 4: Security scan ---
    Write-Host "[4/6] Security scan..." -ForegroundColor White
    $secrets = Test-SensitiveContent -Base $mainBranch -Branch $branch

    if ($secrets.Count -gt 0) {
        Write-Host "  ALERT: Potential secrets detected!" -ForegroundColor Red
        foreach ($s in $secrets) {
            Write-Host "  File: $($s.File)" -ForegroundColor Yellow
            Write-Host "  Match: $($s.Line.Substring(0, [Math]::Min(80, $s.Line.Length)))..." -ForegroundColor Gray
        }
        Write-Host ""
        $proceed = Read-Host "  Continue despite security findings? [y/N]"
        if ($proceed -ne 'y' -and $proceed -ne 'Y') {
            Write-Host "Merge aborted." -ForegroundColor Gray
            return
        }
    }
    else {
        Write-Host "  No secrets detected." -ForegroundColor Green
    }
    Write-Host ""

    # --- Phase 5: Cross-worktree conflict check ---
    Write-Host "[5/6] Cross-worktree overlap check..." -ForegroundColor White
    $branchFiles = @(git diff --name-only "$mainBranch...$branch" 2>&1)
    $overlaps = @()
    foreach ($wt in $worktrees) {
        if ($wt.Branch -eq $branch) { continue }
        $otherFiles = @(git diff --name-only "$mainBranch...$($wt.Branch)" 2>&1)
        $common = $branchFiles | Where-Object { $otherFiles -contains $_ }
        if ($common) {
            $overlaps += [PSCustomObject]@{
                Branch = $wt.Branch
                Files = $common
            }
        }
    }

    if ($overlaps.Count -gt 0) {
        Write-Host "  WARNING: File overlaps with other worktrees:" -ForegroundColor Yellow
        foreach ($o in $overlaps) {
            Write-Host "  vs $($o.Branch):" -ForegroundColor Yellow
            foreach ($f in $o.Files) {
                Write-Host "    $f" -ForegroundColor Gray
            }
        }
        Write-Host ""
        Write-Host "  These worktrees touch the same files. Merge order matters!" -ForegroundColor Yellow
    }
    else {
        Write-Host "  No file overlaps with other worktrees." -ForegroundColor Green
    }
    Write-Host ""

    # --- Phase 6: Merge decision ---
    Write-Host "[6/6] Summary" -ForegroundColor White
    Write-Host "  Branch:     $branch" -ForegroundColor White
    Write-Host "  Target:     $mainBranch" -ForegroundColor White
    Write-Host "  Commits:    $($div.Ahead) ahead, $($div.Behind) behind" -ForegroundColor White
    Write-Host "  Files:      $($div.FilesChanged) changed (+$($div.Additions) -$($div.Deletions))" -ForegroundColor White
    if ($UseSquash) { $strategyLabel = "squash" } else { $strategyLabel = "merge --no-ff" }
    Write-Host "  Strategy:   $strategyLabel" -ForegroundColor White
    Write-Host "  Conflicts:  " -NoNewline
    if ($mergeResult.Clean) {
        Write-Host "none" -ForegroundColor Green
    }
    else {
        Write-Host "$($mergeResult.ConflictFiles.Count) file(s)" -ForegroundColor Red
    }
    Write-Host "  Overlaps:   " -NoNewline
    if ($overlaps.Count -gt 0) {
        Write-Host "$($overlaps.Count) worktree(s)" -ForegroundColor Yellow
    }
    else {
        Write-Host "none" -ForegroundColor Green
    }
    Write-Host ""

    if (-not $mergeResult.Clean) {
        Write-Host "Cannot auto-merge due to conflicts." -ForegroundColor Red
        Write-Host "Options:" -ForegroundColor White
        Write-Host "  1. Rebase first:  cd $($match.Path); git rebase $mainBranch" -ForegroundColor Gray
        Write-Host "  2. Manual merge:  git merge --no-commit --no-ff $branch  (then resolve)" -ForegroundColor Gray
        Write-Host "  3. Abort and fix conflicts in the worktree" -ForegroundColor Gray
        Write-Host ""
        $forceChoice = Read-Host "Attempt manual merge anyway? [y/N]"
        if ($forceChoice -ne 'y' -and $forceChoice -ne 'Y') {
            Write-Host "Merge aborted." -ForegroundColor Gray
            return
        }
        # Manual merge mode
        Write-Host "Starting merge (conflicts will need manual resolution)..." -ForegroundColor Yellow
        git merge --no-commit --no-ff $branch 2>&1
        Write-Host ""
        Write-Host "Merge started with conflicts. Resolve them, then:" -ForegroundColor Yellow
        Write-Host "  git add -A && git commit" -ForegroundColor White
        Write-Host "  OR: git merge --abort" -ForegroundColor White
        return
    }

    # Clean merge - ask for confirmation
    Write-Host "Proceed with merge? [y/N/d(iff)]" -ForegroundColor White
    $choice = Read-Host

    if ($choice -eq 'd' -or $choice -eq 'D') {
        Write-Host ""
        git log --oneline "$mainBranch..$branch" 2>&1
        Write-Host ""
        Write-Host $div.FileStat
        Write-Host ""
        $choice = Read-Host "Proceed with merge? [y/N]"
    }

    if ($choice -ne 'y' -and $choice -ne 'Y') {
        Write-Host "Merge aborted." -ForegroundColor Gray
        return
    }

    # Execute merge
    Write-Host ""
    if ($UseSquash) {
        Write-Host "Executing: git merge --squash $branch" -ForegroundColor Cyan
        git merge --squash $branch 2>&1
        if ($LASTEXITCODE -eq 0) {
            $commitMsg = "Squash merge branch '$branch'"
            git commit -m $commitMsg 2>&1
        }
    }
    else {
        Write-Host "Executing: git merge --no-ff $branch" -ForegroundColor Cyan
        git merge --no-ff $branch 2>&1
    }

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Merge failed!" -ForegroundColor Red
        return
    }

    Write-Host ""
    Write-Host "MERGED SUCCESSFULLY" -ForegroundColor Green
    Write-Host ""

    # Post-merge report
    Write-Host "--- Post-merge report ---" -ForegroundColor Cyan
    $mergedSha = git rev-parse HEAD 2>&1
    Write-Host "  Merge commit: $mergedSha"
    Write-Host "  Strategy:     $strategyLabel"
    Write-Host "  Files:        $($div.FilesChanged) changed (+$($div.Additions) -$($div.Deletions))"
    Write-Host ""

    # Cleanup offer
    if ($match) {
        $cleanup = Read-Host "Remove worktree '$($match.Branch)' and delete branch? [y/N]"
        if ($cleanup -eq 'y' -or $cleanup -eq 'Y') {
            git worktree remove $match.Path --force 2>&1
            if ($LASTEXITCODE -eq 0) {
                Write-Host "Worktree removed: $($match.Path)" -ForegroundColor Green
                git branch -d $branch 2>&1 | Out-Null
                if ($LASTEXITCODE -eq 0) {
                    Write-Host "Branch deleted: $branch" -ForegroundColor Green
                }
            }
        }
    }
}

function Show-ConflictMatrix {
    $mainBranch = Get-MainBranch
    $worktrees = @(Get-Worktrees)

    if ($worktrees.Count -eq 0) {
        Write-Host "No worktrees found." -ForegroundColor Gray
        return
    }

    Write-Host ""
    Write-Host "=== CONFLICT MATRIX ===" -ForegroundColor Cyan
    Write-Host "Base: $mainBranch"
    Write-Host ""

    # Collect all branches (worktrees + main)
    $branches = @($mainBranch) + ($worktrees | ForEach-Object { $_.Branch })

    # Per-branch status vs main
    Write-Host "--- vs $mainBranch ---" -ForegroundColor White
    Write-Host ""
    foreach ($wt in $worktrees) {
        $div = Get-BranchDivergence -Base $mainBranch -Branch $wt.Branch
        $result = Test-MergeTree -Base $mainBranch -Branch $wt.Branch

        if ($result.Clean) { $statusIcon = "[OK]" } else { $statusIcon = "[XX]" }
        if ($result.Clean) { $statusColor = "Green" } else { $statusColor = "Red" }

        Write-Host "  $statusIcon " -ForegroundColor $statusColor -NoNewline
        Write-Host "$($wt.Branch)" -ForegroundColor White -NoNewline
        Write-Host "  ($($div.Ahead)a/$($div.Behind)b, $($div.FilesChanged) files, +$($div.Additions)-$($div.Deletions))" -ForegroundColor Gray

        if (-not $result.Clean) {
            foreach ($c in $result.ConflictFiles) {
                Write-Host "       CONFLICT ($($c.Type)): $($c.File)" -ForegroundColor Red
            }
        }
    }
    Write-Host ""

    # Cross-worktree conflict matrix
    if ($worktrees.Count -gt 1) {
        Write-Host "--- Cross-worktree conflicts ---" -ForegroundColor White
        Write-Host ""

        $pairs = @()
        for ($i = 0; $i -lt $worktrees.Count; $i++) {
            for ($j = $i + 1; $j -lt $worktrees.Count; $j++) {
                $a = $worktrees[$i].Branch
                $b = $worktrees[$j].Branch
                $result = Test-MergeTree -Base $a -Branch $b

                # File overlap check
                $filesA = @(git diff --name-only "$mainBranch...$a" 2>&1)
                $filesB = @(git diff --name-only "$mainBranch...$b" 2>&1)
                $overlap = @($filesA | Where-Object { $filesB -contains $_ })

                if ($result.Clean -and $overlap.Count -eq 0) { $statusIcon = "[OK]" }
                elseif ($overlap.Count -gt 0 -and $result.Clean) { $statusIcon = "[~~]" }
                else { $statusIcon = "[XX]" }
                if ($statusIcon -eq "[OK]") { $statusColor = "Green" }
                elseif ($statusIcon -eq "[~~]") { $statusColor = "Yellow" }
                else { $statusColor = "Red" }

                Write-Host "  $statusIcon " -ForegroundColor $statusColor -NoNewline
                Write-Host "$a" -ForegroundColor White -NoNewline
                Write-Host " vs " -ForegroundColor Gray -NoNewline
                Write-Host "$b" -ForegroundColor White

                if ($overlap.Count -gt 0) {
                    Write-Host "       Overlapping files: $($overlap -join ', ')" -ForegroundColor Yellow
                }
                if (-not $result.Clean) {
                    foreach ($c in $result.ConflictFiles) {
                        Write-Host "       CONFLICT ($($c.Type)): $($c.File)" -ForegroundColor Red
                    }
                }
            }
        }
        Write-Host ""
    }

    # Legend
    Write-Host "Legend: [OK] clean  [~~] file overlap (no conflict yet)  [XX] conflicts" -ForegroundColor Gray
    Write-Host "        Na/Nb = commits ahead/behind" -ForegroundColor Gray

    # Recommended merge order
    Write-Host ""
    Write-Host "--- Recommended merge order ---" -ForegroundColor White

    # Sort by: clean first, then by fewest files changed (least risk first)
    $mergeOrder = $worktrees | ForEach-Object {
        $div = Get-BranchDivergence -Base $mainBranch -Branch $_.Branch
        $result = Test-MergeTree -Base $mainBranch -Branch $_.Branch
        [PSCustomObject]@{
            Branch = $_.Branch
            Clean = $result.Clean
            Files = $div.FilesChanged
            Ahead = $div.Ahead
        }
    } | Sort-Object @{Expression={$_.Clean}; Descending=$true}, @{Expression={$_.Files}}

    $i = 1
    foreach ($m in $mergeOrder) {
        if ($m.Clean) { $icon = "OK" } else { $icon = "FIX FIRST" }
        if ($m.Clean) { $color = "Green" } else { $color = "Red" }
        Write-Host "  $i. " -NoNewline
        Write-Host "$($m.Branch)" -ForegroundColor White -NoNewline
        Write-Host " ($($m.Files) files, $($m.Ahead) commits) " -ForegroundColor Gray -NoNewline
        Write-Host "[$icon]" -ForegroundColor $color
        $i++
    }
    Write-Host ""
}

function Show-Menu {
    $worktrees = @(Get-Worktrees)

    Write-Host ""
    Write-Host "=== DevContainer Worktree Manager ===" -ForegroundColor Cyan
    Write-Host ""

    if ($worktrees.Count -eq 0) {
        Write-Host "  No worktrees found." -ForegroundColor Gray
        Write-Host ""
    }
    else {
        Write-Host "Existing worktrees:" -ForegroundColor White
        $i = 1
        foreach ($wt in $worktrees) {
            $port = Get-WorktreeEnvPort $wt.Path
            if ($port) { $portStr = ":$port" } else { $portStr = "(no .env)" }
            $leaf = Split-Path -Leaf $wt.Path
            $health = Get-WorktreeHealthStatus $wt.Path
            $healthColor = switch ($health) {
                "healthy"     { "Green" }
                "unhealthy"   { "Red" }
                "starting"    { "Yellow" }
                "not running" { "Gray" }
                default       { "White" }
            }
            Write-Host "  [$i] $($wt.Branch)" -ForegroundColor Yellow -NoNewline
            Write-Host "  ($leaf)  $portStr  " -ForegroundColor Gray -NoNewline
            Write-Host "[$health]" -ForegroundColor $healthColor
            $i++
        }
        Write-Host ""
    }

    Write-Host "  [N] Create new worktree" -ForegroundColor Green
    Write-Host "  [M] Merge a worktree into main" -ForegroundColor Cyan
    Write-Host "  [S] Status - conflict matrix" -ForegroundColor Magenta
    Write-Host "  [D] Delete a worktree" -ForegroundColor Red
    Write-Host "  [Q] Quit" -ForegroundColor Gray
    Write-Host ""
    $choice = Read-Host "Choice"

    switch -Regex ($choice) {
        '^[Qq]$' { return }
        '^[Nn]$' {
            $branch = Read-Host "Branch name"
            if ($branch) { New-Worktree -BranchName $branch }
        }
        '^[Mm]$' {
            if ($worktrees.Count -eq 0) {
                Write-Host "Nothing to merge." -ForegroundColor Gray
                return
            }
            $idx = Read-Host "Number to merge"
            if ($idx -match '^\d+$') {
                $target = $worktrees[[int]$idx - 1]
                if ($target) {
                    $sq = Read-Host "Squash merge? [y/N]"
                    $useSquash = ($sq -eq 'y' -or $sq -eq 'Y')
                    Invoke-MergeWorktree -Name $target.Branch -UseSquash:$useSquash
                }
            }
        }
        '^[Ss]$' {
            Show-ConflictMatrix
        }
        '^[Dd]$' {
            if ($worktrees.Count -eq 0) {
                Write-Host "Nothing to delete." -ForegroundColor Gray
                return
            }
            $idx = Read-Host "Number to delete"
            if ($idx -match '^\d+$') {
                $target = $worktrees[[int]$idx - 1]
                if ($target) {
                    Remove-Worktree -Name $target.Branch
                }
            }
        }
        '^\d+$' {
            $idx = [int]$choice
            if ($idx -ge 1 -and $idx -le $worktrees.Count) {
                $target = $worktrees[$idx - 1]
                Open-Worktree -WorktreePath $target.Path
            }
            else {
                Write-Host "Invalid number." -ForegroundColor Red
            }
        }
        default {
            Write-Host "Invalid choice." -ForegroundColor Red
        }
    }
}

# --- Main ---

if ($Rebuild) {
    Invoke-RebuildWorktree -Name $Rebuild
}
elseif ($Health) {
    Show-WorktreeHealth -Name $Health
}
elseif ($Merge) {
    Invoke-MergeWorktree -Name $Merge -UseSquash:$Squash
}
elseif ($Status) {
    Show-ConflictMatrix
}
elseif ($New) {
    New-Worktree -BranchName $New
}
elseif ($Open) {
    $worktrees = @(Get-Worktrees)
    $match = Find-WorktreeByName -Name $Open -Worktrees $worktrees
    if ($match) {
        Open-Worktree -WorktreePath $match.Path
    }
    else {
        Write-Host "Worktree not found: $Open" -ForegroundColor Red
    }
}
elseif ($Remove) {
    Remove-Worktree -Name $Remove
}
else {
    Show-Menu
}
