import fs from 'fs-extra';
import path from 'path';
import type { Extension, EnvRequirement } from './extensions.js';

interface EnvGroup {
  extensionName: string;
  requirements: EnvRequirement[];
}

/**
 * Collect all envRequirements from installed extensions, grouped by extension.
 */
export function collectEnvRequirements(extensions: Extension[]): EnvGroup[] {
  const groups: EnvGroup[] = [];
  for (const ext of extensions) {
    if (ext.envRequirements && ext.envRequirements.length > 0) {
      groups.push({
        extensionName: ext.name,
        requirements: ext.envRequirements,
      });
    }
  }
  return groups;
}

/**
 * Get list of missing required env variables (not set in process.env).
 * Returns array of { extensionName, requirement } for each missing required var.
 */
export function getMissingRequiredEnv(
  extensions: Extension[]
): Array<{ extensionName: string; requirement: EnvRequirement }> {
  const missing: Array<{ extensionName: string; requirement: EnvRequirement }> = [];
  for (const ext of extensions) {
    if (!ext.envRequirements) continue;
    for (const req of ext.envRequirements) {
      if (req.required && !process.env[req.name]) {
        missing.push({ extensionName: ext.name, requirement: req });
      }
    }
  }
  return missing;
}

/**
 * Generate .env.example file in projectPath with env requirements from all extensions.
 * Required vars are uncommented, optional vars are commented out.
 * Returns list of missing required env variable names.
 */
export async function generateEnvExample(
  projectPath: string,
  extensions: Extension[]
): Promise<string[]> {
  const groups = collectEnvRequirements(extensions);
  if (groups.length === 0) return [];

  const lines: string[] = [
    '# ============================================',
    '# dev-pomogator — environment variables',
    '# Generated by installer. Copy to .env and fill values.',
    '# ============================================',
    '',
  ];

  for (const group of groups) {
    lines.push(`# --- ${group.extensionName} ---`);

    for (const req of group.requirements) {
      const label = req.required ? '[REQUIRED]' : '[optional]';
      const descLine = `# ${label} ${req.description}`;
      const valuePart = req.example || req.default || '';

      if (req.required) {
        lines.push(descLine);
        lines.push(`${req.name}=${valuePart}`);
      } else {
        lines.push(descLine);
        lines.push(`# ${req.name}=${valuePart}`);
      }
      lines.push('');
    }
  }

  const envExamplePath = path.join(projectPath, '.env.example');
  await fs.writeFile(envExamplePath, lines.join('\n'), 'utf-8');

  // Return missing required vars
  const missing = getMissingRequiredEnv(extensions);
  return missing.map((m) => m.requirement.name);
}
