// architecture-research-workflow Stage 7 — merge stage outputs into RESEARCH.md.
//
// Reads every `.specs/<slug>/.architecture-research/<N>-<stage>.md`, in
// stage order, and rewrites `.specs/<slug>/RESEARCH.md` with one
// Appendix per stage. The top of RESEARCH.md gets a fresh table of
// contents; the rest of the body is regenerated from the stage files —
// hand-written content in the OLD RESEARCH.md is overwritten by design.
// (Stage files are the source of truth post-Stage-7; whatever stage 6
// hand-off carries forward should be folded into stage 6 not RESEARCH.md.)
//
// Sets a sentinel marker in `.specs/<slug>/.architecture-research/.done`
// so that `create-spec` can detect the `--research-done` state without
// re-parsing RESEARCH.md.

import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { STAGES } from './init.ts';

export interface MergeOptions {
  repoRoot: string;
  slug: string;
}

export interface MergeResult {
  researchMdPath: string;
  doneMarkerPath: string;
  stagesIncluded: number;
  stagesMissing: string[];
}

function stageDir(repoRoot: string, slug: string): string {
  return path.join(repoRoot, '.specs', slug, '.architecture-research');
}

export function mergeStages(opts: MergeOptions): MergeResult {
  const dir = stageDir(opts.repoRoot, opts.slug);
  if (!fs.existsSync(dir)) {
    throw new Error(
      `[arch-research-workflow] stage dir does not exist: ${dir} (run init.ts first)`,
    );
  }

  const stagesMissing: string[] = [];
  const bodies: Array<{ num: number; title: string; body: string }> = [];
  for (const stage of STAGES) {
    const file = path.join(dir, `${stage.num}-${stage.slug}.md`);
    if (!fs.existsSync(file)) {
      stagesMissing.push(`${stage.num}-${stage.slug}.md`);
      continue;
    }
    bodies.push({
      num: stage.num,
      title: stage.title,
      body: fs.readFileSync(file, 'utf8'),
    });
  }

  // Compose RESEARCH.md with TOC + one Appendix per stage.
  const lines: string[] = [];
  lines.push('# RESEARCH.md');
  lines.push('');
  lines.push(
    '_Generated by `architecture-research-workflow` Stage 7. ' +
      'Edits to this file are overwritten on re-merge — change the ' +
      'underlying stage file under `.architecture-research/` instead._',
  );
  lines.push('');
  lines.push('## Table of contents');
  for (const b of bodies) {
    const anchor = `appendix-stage-${b.num}-${STAGES[b.num - 1].slug}`;
    lines.push(`- [Stage ${b.num} — ${b.title}](#${anchor})`);
  }
  lines.push('');
  for (const b of bodies) {
    const anchor = `appendix-stage-${b.num}-${STAGES[b.num - 1].slug}`;
    lines.push(`## <a name="${anchor}"></a>Appendix — Stage ${b.num}: ${b.title}`);
    lines.push('');
    lines.push(`> Source: \`.architecture-research/${b.num}-${STAGES[b.num - 1].slug}.md\``);
    lines.push('');
    lines.push(b.body.trim());
    lines.push('');
  }

  const researchMdPath = path.join(opts.repoRoot, '.specs', opts.slug, 'RESEARCH.md');
  fs.mkdirSync(path.dirname(researchMdPath), { recursive: true });
  fs.writeFileSync(researchMdPath, lines.join('\n') + '\n');

  // Sentinel — `create-spec` reads this to know the heavier flow ran.
  const doneMarkerPath = path.join(dir, '.done');
  fs.writeFileSync(
    doneMarkerPath,
    JSON.stringify({
      generated_at: new Date().toISOString(),
      stages_included: bodies.length,
      stages_missing: stagesMissing,
    }, null, 2) + '\n',
  );

  return {
    researchMdPath,
    doneMarkerPath,
    stagesIncluded: bodies.length,
    stagesMissing,
  };
}

function isMain(): boolean {
  if (!process.argv[1]) return false;
  return import.meta.url === pathToFileURL(process.argv[1]).href;
}

if (isMain()) {
  const slugIndex = process.argv.findIndex((a) => a === '--slug');
  if (slugIndex === -1 || !process.argv[slugIndex + 1]) {
    process.stderr.write('Usage: merge.ts --slug <name>\n');
    process.exit(1);
  }
  const result = mergeStages({
    repoRoot: process.env.DEV_POMOGATOR_REPO_ROOT ?? process.cwd(),
    slug: process.argv[slugIndex + 1],
  });
  process.stdout.write(JSON.stringify(result, null, 2) + '\n');
}
