Feature: claim-sanity-check

  # Generated by `scenario-writer` resolver from `FR.md`. Each scenario is a skeleton — test authors MUST fill in real step implementations.

  Background:
    # Define preconditions and test setup here

  @feature1
  Scenario: FR-1 — {Название}
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature2
  Scenario: FR-2 — {Название}
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature3
  Scenario: FR-3 — {Название}
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature4
  Scenario: FR-4 — {Название}
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature5
  Scenario: FR-5 — {Название}
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.
