// ac-author resolver — given a backlog entry for missing ACCEPTANCE_CRITERIA.md,
// reads the spec's FR.md, extracts every FR-N heading, and generates a skeleton
// ACCEPTANCE_CRITERIA.md with one AC section per FR (WHEN/THEN/SHALL placeholders).
//
// Mechanical — no LLM call. Authors fill in real criteria later.
//
// Idempotent: if ACCEPTANCE_CRITERIA.md already exists, returns notes saying so.

import fs from 'node:fs';
import path from 'node:path';
import type { Resolver, ResolverResult } from './types.ts';
import type { BacklogEntry } from '../types.ts';

const FR_HEADING_RE = /^#{2,3}\s+(?:Requirement:\s+)?(FR-\d+)(?::?\s+([^\n]+))?/gm;

export const acAuthor: Resolver = {
  name: 'ac-author',
  description:
    'Generates skeleton ACCEPTANCE_CRITERIA.md from the spec\'s FR.md headings — one AC section per FR-N with EARS WHEN/THEN placeholders.',

  async resolve(opts): Promise<ResolverResult> {
    return acAuthorImpl(opts.repoRoot, opts.entry);
  },
};

function acAuthorImpl(repoRoot: string, entry: BacklogEntry): ResolverResult {
  const specDir = path.join(repoRoot, '.specs', entry.slug);
  const frFile = path.join(specDir, 'FR.md');
  const acFile = path.join(specDir, 'ACCEPTANCE_CRITERIA.md');

  if (!fs.existsSync(frFile)) {
    return {
      confidence: 0,
      files_changed: [],
      notes: `${entry.slug}/FR.md not found — cannot derive AC list.`,
      bailed_out: { reason: 'fr-md-missing' },
    };
  }
  if (fs.existsSync(acFile)) {
    return {
      confidence: 1,
      files_changed: [],
      notes: `${entry.slug}/ACCEPTANCE_CRITERIA.md already exists — nothing to create.`,
      bailed_out: { reason: 'already-exists' },
    };
  }

  const frBody = fs.readFileSync(frFile, 'utf8');
  const frs: Array<{ id: string; title: string }> = [];
  let m: RegExpExecArray | null;
  FR_HEADING_RE.lastIndex = 0;
  while ((m = FR_HEADING_RE.exec(frBody)) !== null) {
    frs.push({ id: m[1], title: (m[2] ?? '').trim() });
  }
  if (frs.length === 0) {
    return {
      confidence: 0,
      files_changed: [],
      notes: `${entry.slug}/FR.md contains no \`## FR-N\` headings — nothing to derive AC from.`,
      bailed_out: { reason: 'no-fr-headings' },
    };
  }

  const lines: string[] = [
    `# Acceptance Criteria — ${entry.slug}`,
    '',
    `> Generated by \`ac-author\` resolver from \`FR.md\`. **Each AC is a skeleton — fill in the WHEN/THEN with real preconditions and expected behavior.**`,
    '',
    `Source: FR.md (\`${frs.length}\` requirements detected).`,
    '',
    '---',
    '',
  ];
  for (const fr of frs) {
    const titleSuffix = fr.title ? ` — ${fr.title}` : '';
    const num = fr.id.replace(/^FR-/, '');
    lines.push(`## AC-${num} (${fr.id})${titleSuffix}`);
    lines.push('');
    lines.push(`**Requirement:** [${fr.id}](FR.md#${fr.id.toLowerCase()})`);
    lines.push('');
    lines.push(`WHEN \`<precondition or event>\``);
    lines.push(`THEN system SHALL \`<expected observable behaviour>\``);
    lines.push('');
    lines.push(`> \`[TBD]\` — ac-author placeholder. Refine before STOP gate.`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  fs.writeFileSync(acFile, lines.join('\n'));

  return {
    confidence: 0.8,
    files_changed: [path.relative(repoRoot, acFile)],
    notes:
      `Generated skeleton ACCEPTANCE_CRITERIA.md with ${frs.length} AC sections ` +
      `(one per FR-N). Each section has EARS WHEN/THEN placeholder marked [TBD] ` +
      `— spec author MUST fill in real preconditions and expected behaviour ` +
      `before the spec advances to the STOP gate.`,
  };
}
