// scenario-writer resolver — given a backlog entry for missing test coverage (missing-test),
// reads the spec's FR.md, extracts FR-N headings, and generates a .feature file with
// one Scenario per FR (Given/When/Then placeholders). Idempotent: if a @featureN tag
// already exists in the .feature file, bails out.
//
// Mechanical — no LLM call. Test authors fill in real step implementations later.

import fs from 'node:fs';
import path from 'node:path';
import type { Resolver, ResolverResult } from './types.ts';
import type { BacklogEntry } from '../types.ts';

const FR_HEADING_RE = /^#{2,3}\s+(?:Requirement:\s+)?(FR-\d+)(?::?\s+([^\n]+))?/gm;

export const scenarioWriter: Resolver = {
  name: 'scenario-writer',
  description:
    'Generates skeleton .feature file with one Scenario per FR-N — @featureN tag + Given/When/Then placeholders for test authors to implement.',

  async resolve(opts): Promise<ResolverResult> {
    return scenarioWriterImpl(opts.repoRoot, opts.entry);
  },
};

function scenarioWriterImpl(repoRoot: string, entry: BacklogEntry): ResolverResult {
  const specDir = path.join(repoRoot, '.specs', entry.slug);
  const frFile = path.join(specDir, 'FR.md');
  const featureFile = path.join(specDir, `${entry.slug}.feature`);

  if (!fs.existsSync(frFile)) {
    return {
      confidence: 0,
      files_changed: [],
      notes: `${entry.slug}/FR.md not found — cannot derive test scenarios.`,
      bailed_out: { reason: 'fr-md-missing' },
    };
  }

  const frBody = fs.readFileSync(frFile, 'utf8');
  const frs: Array<{ id: string; title: string }> = [];
  let m: RegExpExecArray | null;
  FR_HEADING_RE.lastIndex = 0;
  while ((m = FR_HEADING_RE.exec(frBody)) !== null) {
    frs.push({ id: m[1], title: (m[2] ?? '').trim() });
  }
  if (frs.length === 0) {
    return {
      confidence: 0,
      files_changed: [],
      notes: `${entry.slug}/FR.md contains no \`## FR-N\` headings — nothing to derive test scenarios from.`,
      bailed_out: { reason: 'no-fr-headings' },
    };
  }

  // Check if .feature file already exists and contains any @featureN tags
  if (fs.existsSync(featureFile)) {
    const featureBody = fs.readFileSync(featureFile, 'utf8');
    const hasFeatureTags = /@feature\d+/.test(featureBody);
    if (hasFeatureTags) {
      return {
        confidence: 1,
        files_changed: [],
        notes: `${entry.slug}/${entry.slug}.feature already exists with @featureN tags — test scenarios already scaffolded.`,
        bailed_out: { reason: 'already-covered' },
      };
    }
  }

  // Build .feature file content
  const lines: string[] = [
    `Feature: ${entry.slug}`,
    '',
    `  # Generated by \`scenario-writer\` resolver from \`FR.md\`. Each scenario is a skeleton — test authors MUST fill in real step implementations.`,
    '',
    `  Background:`,
    `    # Define preconditions and test setup here`,
    '',
  ];

  for (const fr of frs) {
    const titleSuffix = fr.title ? ` — ${fr.title}` : '';
    const num = fr.id.replace(/^FR-/, '');
    lines.push(`  @feature${num}`);
    lines.push(`  Scenario: ${fr.id}${titleSuffix}`);
    lines.push(`    Given \`<precondition or initial state>\``);
    lines.push(`    When \`<action or event>\``);
    lines.push(`    Then \`<expected observable result>\``);
    lines.push('');
    lines.push(`    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.`);
    lines.push('');
  }

  fs.writeFileSync(featureFile, lines.join('\n'));

  return {
    confidence: 0.8,
    files_changed: [path.relative(repoRoot, featureFile)],
    notes:
      `Generated skeleton .feature file with ${frs.length} Scenario blocks ` +
      `(one per FR-N), each tagged with @featureN and Given/When/Then placeholders ` +
      `marked [TBD]. Test authors MUST implement step definitions in the step runner ` +
      `(e.g., Gherkin adapter, Cucumber, or language-specific BDD framework) ` +
      `before advancing to the STOP gate.`,
  };
}
