import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { CheckDefinition } from '../types.js';
import { buildResult, fileExists } from './_helpers.js';

/**
 * Context menu install drift (Windows, opt-in feature).
 *
 * `/context-menu` writes artifacts outside the repo/plugin tree that never auto-refresh:
 *   1. ~/.dev-pomogator/scripts/launch-claude-tui.ps1 (copied from the bundled script)
 *   2. ~/.dev-pomogator/scripts/launch-Codex-tui.ps1 (copied from the bundled script)
 *   3. C:\Program Files\Nilesoft Shell\imports\claude-code.nss (generated by generateNss())
 *   4. C:\Program Files\Nilesoft Shell\imports\Codex.nss (generated by generateCodexNss())
 *
 * Editing tools/context-menu/postinstall.ts or bundled launch scripts in the plugin tree
 * does NOT update either installed copy — the right-click menu keeps running the OLD code
 * forever until `/context-menu` is re-run by hand. Caught 2026-06-30: a YOLO-entry trust-gate
 * fix shipped in the plugin, but the user's installed NSS + launch script were still the
 * pre-fix version, so the right-click menu kept failing identically after the "fix".
 *
 * Gated to Windows + only when context-menu was actually set up (NSS file present) — this is an
 * opt-in feature, the doctor must not nag users who never ran `/context-menu`.
 */
const META = {
  id: 'C-CTXM',
  fr: 'FR-CTXM',
  name: 'Context menu install drift (Windows)',
  group: 'self-sufficient' as const,
  reinstallable: true,
};

const CLAUDE_NSS = 'C:\\Program Files\\Nilesoft Shell\\imports\\claude-code.nss';
const CODEX_NSS = 'C:\\Program Files\\Nilesoft Shell\\imports\\Codex.nss';

export const contextMenuCheck: CheckDefinition = {
  ...META,
  pool: 'fs',
  gate() {
    if (process.platform !== 'win32') {
      return { relevant: false, reason: 'context menu is a Windows-only (Nilesoft Shell) feature' };
    }
    if (!fileExists(CLAUDE_NSS) && !fileExists(CODEX_NSS)) {
      return { relevant: false, reason: 'context menu never set up (run /context-menu to opt in) — nothing to drift-check' };
    }
    return { relevant: true };
  },
  async run(ctx) {
    const home = ctx.homeDir || os.homedir();
    const installedClaudeLaunchScript = path.join(home, '.dev-pomogator', 'scripts', 'launch-claude-tui.ps1');
    const installedCodexLaunchScript = path.join(home, '.dev-pomogator', 'scripts', 'launch-Codex-tui.ps1');

    const hasClaudeChannel = fileExists(CLAUDE_NSS) || fileExists(installedClaudeLaunchScript);
    const hasCodexChannel = fileExists(CODEX_NSS) || fileExists(installedCodexLaunchScript);
    const fixHint = hasCodexChannel && !hasClaudeChannel
      ? 'Apply NOW: powershell -ExecutionPolicy Bypass -File .\\scripts\\install-codex-context-menu.ps1 -PostinstallOnly ' +
        '(re-copies the Codex launch script + regenerates Codex.nss + reloads Nilesoft Shell).'
      : 'Apply NOW: node -e "require(require(\'path\').join(process.env.CLAUDE_PLUGIN_ROOT||\'.\',\'tools\',\'_shared\',\'bootstrap.cjs\'))" -- "tools/context-menu/postinstall.ts" ' +
        '(re-copies launch scripts + regenerates NSS files + reloads Nilesoft Shell — same steps /context-menu runs).';

    let mod: typeof import('../../../../../../tools/context-menu/postinstall.ts');
    try {
      mod = await import('../../../../../../tools/context-menu/postinstall.ts');
    } catch (e) {
      return buildResult(META, 'warning', `could not load postinstall.ts to compare: ${(e as Error).message}`, {
        hint: fixHint,
      });
    }

    const drift: string[] = [];

    function compareInstalledFile(label: string, bundledPath: string, installedPath: string): void {
      const bundled = fs.readFileSync(bundledPath, 'utf-8');
      const installed = fileExists(installedPath)
        ? fs.readFileSync(installedPath, 'utf-8')
        : null;
      if (installed === null) {
        drift.push(`${label} not installed at all`);
      } else if (installed !== bundled) {
        drift.push(`${label} is stale (plugin source changed since last /context-menu run)`);
      }
    }

    if (hasClaudeChannel) {
      try {
        compareInstalledFile('launch-claude-tui.ps1', mod.bundledLaunchScriptPath(), installedClaudeLaunchScript);
      } catch (e) {
        drift.push(`could not compare Claude launch script: ${(e as Error).message}`);
      }
    }

    if (hasCodexChannel) {
      try {
        compareInstalledFile('launch-Codex-tui.ps1', mod.bundledCodexLaunchScriptPath(), installedCodexLaunchScript);
      } catch (e) {
        drift.push(`could not compare Codex launch script: ${(e as Error).message}`);
      }
    }

    if (hasClaudeChannel) {
      try {
        const currentNss = mod.generateNss();
        const installedNss = fileExists(CLAUDE_NSS) ? fs.readFileSync(CLAUDE_NSS, 'utf-8') : null;
        if (installedNss === null) {
          drift.push('claude-code.nss menu is not installed');
        } else if (installedNss !== currentNss) {
          drift.push('claude-code.nss menu is stale (does not match what generateNss() would produce now)');
        }
      } catch (e) {
        drift.push(`could not compare Claude NSS content: ${(e as Error).message}`);
      }
    }

    if (hasCodexChannel) {
      try {
        const currentNss = mod.generateCodexNss();
        const installedNss = fileExists(CODEX_NSS) ? fs.readFileSync(CODEX_NSS, 'utf-8') : null;
        if (installedNss === null) {
          drift.push('Codex.nss menu is not installed');
        } else if (installedNss !== currentNss) {
          drift.push('Codex.nss menu is stale (does not match what generateCodexNss() would produce now)');
        }
      } catch (e) {
        drift.push(`could not compare Codex NSS content: ${(e as Error).message}`);
      }
    }

    if (drift.length === 0) {
      return buildResult(META, 'ok', 'installed context-menu launch scripts + NSS files match the current plugin source');
    }

    return buildResult(
      META,
      'warning',
      `right-click Claude/Codex menu is running stale code: ${drift.join('; ')}`,
      { hint: fixHint, details: { fixAction: 'context-menu-postinstall', drift } },
    );
  },
};
