# Tasks

## Task Summary Table

<!-- auto-generated by spec-status.ts -Format task-table; do not edit manually -->
| ID | Title | Status | Depends | Phase | Est. |
|----|-------|--------|---------|-------|------|
| TBD-1 | {first task} | TODO | — | Phase 0 | 30m |
<!-- end auto-generated -->

> Regenerate via `Skill("task-board-forms")` or `npx tsx extensions/specs-workflow/tools/specs-generator/spec-status.ts -Path .specs/{slug} -Format task-table` and splice between markers.

## TDD Workflow

> Задачи организованы по TDD: Red -> Green -> Refactor.
> Каждый этап реализации начинается с .feature сценария (Red), затем реализация (Green), затем рефакторинг.

## Phase -1: Infrastructure Prerequisites (опционально)

> Подготовить инфраструктуру ПЕРЕД разработкой.
> Пропустить если фича не требует новых сервисов/БД/конфигов.
> Env vars пометить `[VERIFIED: source]` после проверки через официальную документацию.

- [ ] {Создать/обновить docker-compose сервисы}
- [ ] {Создать .env файл с необходимыми переменными}
- [ ] {Создать/обновить базу данных / миграции}
- [ ] {Настроить secrets / credentials}

## Phase 0: BDD Foundation (Red)

> Создать .feature файл, step definitions, и BDD hooks ПЕРЕД реализацией бизнес-логики.
> Все сценарии должны FAIL (Red) на этом этапе.
>
> **Если DESIGN.md `**Framework:**` = "framework missing" (Evidence = not installed)** — Phase 0 ОБЯЗАН содержать **bootstrap block** из 3 task в строгой последовательности (все implementation tasks зависят от последней):
>
> ```
> - [ ] Install {framework}: {installCommand}          — id: install-bdd-framework
>   _Source: DESIGN.md "## BDD Test Infrastructure" > Install Command_
> - [ ] Bootstrap Hooks folder {hookFileHints}         — id: bootstrap-bdd-hooks
>   _depends: install-bdd-framework_
>   _Stubs: BeforeAll / AfterAll / BeforeScenario / AfterScenario per framework convention_
>   _Reqnroll: `[BeforeScenario]` / `[AfterScenario]` attributes; Cucumber.js: `Before()` / `After()`; Behave: `before_scenario` в environment.py; pytest-bdd: fixtures с `autouse=True`_
> - [ ] Create fixtures folder {fixturesFolderHint} + framework config {configFileHint}  — id: bootstrap-bdd-fixtures-config
>   _depends: bootstrap-bdd-hooks_
>   _Min valid content: `{}` для reqnroll.json; `module.exports = {}` для cucumber.js; `[behave]\nshow_skipped=false` для behave.ini; `[pytest]\nbdd_features_base_dir=features/` для pytest.ini_
> ```
>
> Все implementation tasks (Phase 1+) SHALL содержать `_depends: bootstrap-bdd-fixtures-config_`.
>
> **Если Framework уже установлен (Evidence positive)** — bootstrap block заменяется одной строкой:
> `(BDD foundation already in place, verified in DESIGN.md Evidence: {evidence_line})`
>
> **Если DESIGN.md содержит `TEST_DATA_ACTIVE`** — добавить задачу для каждого hook из DESIGN.md "Новые hooks" и каждого fixture из "Test Data & Fixtures" (в дополнение к bootstrap block).
> Если `TEST_DATA_NONE` — дополнительные hook/fixture задачи не нужны (bootstrap block всё равно обязателен при missing framework).

- [ ] {Создать/обновить .feature файл с BDD сценариями}
- [ ] {Создать step definitions (заглушки с PendingStepException/throw)}
- [ ] {Создать hook: `{путь}` ({тип}, {scope}) — cleanup для {описание данных}}
  _Source: DESIGN.md "BDD Test Infrastructure" > "Новые hooks"_
  _Reuse: {путь к существующему hook, если применимо}_
- [ ] {Создать fixture: `{путь}` — {назначение}, lifecycle: {per-scenario/per-feature/shared}}
  _Source: DESIGN.md "BDD Test Infrastructure" > "Test Data & Fixtures"_
- [ ] {Убедиться что все сценарии FAIL (Red)}

## Phase 1: {Этап реализации 1} (Green)

> Реализовать код, чтобы BDD сценарии начали проходить.
> Each task below must pass `task-form-guard`: `**Done When:**` with ≥1 checkbox, `Status: TODO|IN_PROGRESS|DONE|BLOCKED`, `Est: <N>m`.

- [ ] {Задача 1.1} -- @featureN — Status: TODO | Est: 30m
  _Requirements: [FR-N](FR.md#fr-n-{название})_
  **Done When:**
  - [ ] {binary observable 1 — file exists / API returns X / log shows Y}
  - [ ] @featureN scenario переходит из Red в Green
- [ ] {Задача 1.2} -- @featureN — Status: TODO | Est: 45m
  _Requirements: [FR-N](FR.md#fr-n-{название})_
  **Done When:**
  - [ ] {binary observable}
  - [ ] @featureN scenario passes
- [ ] {Verify: сценарии @featureN переходят из Red в Green}

## Phase 2: {Этап реализации 2} (Green)

- [ ] {Задача 2.1} -- @featureN — Status: TODO | Est: 30m
  _Requirements: [FR-N](FR.md#fr-n-{название})_
  **Done When:**
  - [ ] {binary observable}
  - [ ] @featureN scenario passes
- [ ] {Задача 2.2} -- @featureN — Status: TODO | Est: 45m
  _Requirements: [FR-N](FR.md#fr-n-{название})_
  **Done When:**
  - [ ] {binary observable}
  - [ ] @featureN scenario passes
- [ ] {Verify: сценарии @featureN переходят из Red в Green}

## Phase 3: Refactor & Polish

- [ ] {Рефакторинг после прохождения всех сценариев} — Status: TODO | Est: 30m
  **Done When:**
  - [ ] Все BDD сценарии GREEN
  - [ ] Code duplication score (jscpd) ≤ baseline
- [ ] Final verification — Status: TODO | Est: 15m
  **Done When:**
  - [ ] `validate-spec.ts -Path .specs/{slug}` → 0 errors
  - [ ] `audit-spec.ts -Path .specs/{slug}` → 0 findings
  - [ ] `/simplify` final review clean
