<<<<<<<< HEAD:.specs/spec-mcp-usability-dogfood/spec-mcp-usability-dogfood.feature
# Каждый Scenario ОБЯЗАН нести @FR-N тег требования, которое он тестирует
# (conformance UNTAGGED_SCENARIO; blanket-теги ловит TAG_BULK_SUSPECT + FR-8 judge).
Feature: {DOMAIN}{NNN}_{Название_фичи}
========
Feature: docker-win-test

  # Generated by `scenario-writer` resolver from `FR.md`. Each scenario is a skeleton — test authors MUST fill in real step implementations.
>>>>>>>> feat/phase-2a-mcp-server-and-hooks:.specs/docker-win-test/docker-win-test.feature

  Background:
    # Define preconditions and test setup here

<<<<<<<< HEAD:.specs/spec-mcp-usability-dogfood/spec-mcp-usability-dogfood.feature
  @FR-1
  Scenario: {DOMAIN}{NNN+1}_{Название_сценария_1}
    Given {контекст}
    When {действие}
    Then {ожидаемый результат}

  @FR-2
  Scenario: {DOMAIN}{NNN+2}_{Название_сценария_2}
    Given {контекст}
    When {действие}
    Then {ожидаемый результат}

  @FR-3
  Scenario: {DOMAIN}{NNN+3}_{Название_сценария_3}
    Given {контекст}
    When {действие}
    Then {ожидаемый результат}
========
  @feature1
  Scenario: FR-1 — Docker-based Win test VM via dockur/windows @feature1
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature2
  Scenario: FR-2 — OEM post-install automation @feature2
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`
>>>>>>>> feat/phase-2a-mcp-server-and-hooks:.specs/docker-win-test/docker-win-test.feature

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature3
  Scenario: FR-3 — Fixture management via docker-fixture.ps1 @feature3
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature4
  Scenario: FR-4 — Physical fixture storage @feature4
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature5
  Scenario: FR-5 — GUI access via noVNC + RDP @feature5
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature6
  Scenario: FR-6 — Local ISO cache @feature6
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.

  @feature7
  Scenario: FR-7 — Integration with test catalog @feature7
    Given `<precondition or initial state>`
    When `<action or event>`
    Then `<expected observable result>`

    # [TBD] scenario-writer placeholder. Implement step definitions before shipping.
