import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { CheckDefinition } from '../types.js';
import { buildResult, fileExists } from './_helpers.js';

/**
 * Context menu install drift (Windows, opt-in feature).
 *
 * `/context-menu` writes TWO artifacts outside the repo/plugin tree that never auto-refresh:
 *   1. ~/.dev-pomogator/scripts/launch-claude-tui.ps1 (copied from the bundled script)
 *   2. C:\Program Files\Nilesoft Shell\imports\claude-code.nss (generated by generateNss())
 *
 * Editing tools/context-menu/postinstall.ts or scripts/launch-claude-tui.ps1 in the plugin tree
 * does NOT update either installed copy — the right-click menu keeps running the OLD code
 * forever until `/context-menu` is re-run by hand. Caught 2026-06-30: a YOLO-entry trust-gate
 * fix shipped in the plugin, but the user's installed NSS + launch script were still the
 * pre-fix version, so the right-click menu kept failing identically after the "fix".
 *
 * Gated to Windows + only when context-menu was actually set up (NSS file present) — this is an
 * opt-in feature, the doctor must not nag users who never ran `/context-menu`.
 */
const META = {
  id: 'C-CTXM',
  fr: 'FR-CTXM',
  name: 'Context menu install drift (Windows)',
  group: 'self-sufficient' as const,
  reinstallable: true,
};

const NILESOFT_NSS = 'C:\\Program Files\\Nilesoft Shell\\imports\\claude-code.nss';

export const contextMenuCheck: CheckDefinition = {
  ...META,
  pool: 'fs',
  gate() {
    if (process.platform !== 'win32') {
      return { relevant: false, reason: 'context menu is a Windows-only (Nilesoft Shell) feature' };
    }
    if (!fileExists(NILESOFT_NSS)) {
      return { relevant: false, reason: 'context menu never set up (run /context-menu to opt in) — nothing to drift-check' };
    }
    return { relevant: true };
  },
  async run(ctx) {
    const home = ctx.homeDir || os.homedir();
    const installedLaunchScript = path.join(home, '.dev-pomogator', 'scripts', 'launch-claude-tui.ps1');

    const fixHint =
      'Apply NOW: node -e "require(require(\'path\').join(process.env.CLAUDE_PLUGIN_ROOT||\'.\',\'tools\',\'_shared\',\'bootstrap.cjs\'))" -- "tools/context-menu/postinstall.ts" ' +
      '(re-copies the launch script + regenerates the NSS + reloads Nilesoft Shell — same steps /context-menu runs).';

    let mod: typeof import('../../../../../../tools/context-menu/postinstall.ts');
    try {
      mod = await import('../../../../../../tools/context-menu/postinstall.ts');
    } catch (e) {
      return buildResult(META, 'warning', `could not load postinstall.ts to compare: ${(e as Error).message}`, {
        hint: fixHint,
      });
    }

    const drift: string[] = [];

    try {
      const bundled = fs.readFileSync(mod.bundledLaunchScriptPath(), 'utf-8');
      const installed = fileExists(installedLaunchScript)
        ? fs.readFileSync(installedLaunchScript, 'utf-8')
        : null;
      if (installed === null) {
        drift.push('launch-claude-tui.ps1 not installed at all');
      } else if (installed !== bundled) {
        drift.push('launch-claude-tui.ps1 is stale (plugin source changed since last /context-menu run)');
      }
    } catch (e) {
      drift.push(`could not compare launch script: ${(e as Error).message}`);
    }

    try {
      const currentNss = mod.generateNss();
      const installedNss = fs.readFileSync(NILESOFT_NSS, 'utf-8');
      if (installedNss !== currentNss) {
        drift.push('claude-code.nss menu is stale (does not match what generateNss() would produce now)');
      }
    } catch (e) {
      drift.push(`could not compare NSS content: ${(e as Error).message}`);
    }

    if (drift.length === 0) {
      return buildResult(META, 'ok', 'installed context-menu launch script + NSS match the current plugin source');
    }

    return buildResult(
      META,
      'warning',
      `right-click "Claude Code" menu is running stale code: ${drift.join('; ')}`,
      { hint: fixHint, details: { fixAction: 'context-menu-postinstall', drift } },
    );
  },
};
