/**
 * env-sync — FR-10: copy lost local env/config files into a fresh worktree.
 *
 * `git worktree add` checks out only committed files, so gitignored root `.env*`
 * (e.g. `.env.test`) are absent in a new worktree. This module copies them from
 * main, regenerates `.devcontainer/.env` with worktree-unique ports (never copies
 * it — port collision), warns on secret-bearing files (no value printed), and
 * skips files that already exist. Best-effort: a per-file failure is logged and
 * skipped, never aborting. Each action is appended to the env-sync audit JSONL.
 *
 * Pure Node stdlib + git CLI; no external deps.
 */
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const SECRET_PATTERNS = [
  /password/i,
  /secret/i,
  /api[_-]?key/i,
  /token/i,
  /BEGIN (RSA |EC |DSA )?PRIVATE KEY/,
];

export type EnvSyncAction = 'copied' | 'regenerated' | 'skipped' | 'warned';

export interface EnvSyncResult {
  file: string;
  action: EnvSyncAction;
  secretDetected: boolean;
}

/** Append one JSONL audit line; never throws (observability is non-critical). */
function appendAudit(worktreePath: string, r: EnvSyncResult): void {
  try {
    const logDir = path.join(os.homedir(), '.dev-pomogator', 'logs');
    fs.mkdirSync(logDir, { recursive: true });
    const line =
      JSON.stringify({
        ts: new Date().toISOString(),
        worktree_path: worktreePath,
        file: r.file,
        action: r.action,
        secret_detected: r.secretDetected,
      }) + '\n';
    fs.appendFileSync(path.join(logDir, 'worktree-env-sync.jsonl'), line);
  } catch {
    /* non-fatal */
  }
}

/** List repo-root `.env*` files that are gitignored in main (candidate set). */
function listCandidateEnvFiles(mainPath: string): string[] {
  const entries = fs.readdirSync(mainPath, { withFileTypes: true });
  const out: string[] = [];
  for (const e of entries) {
    if (!e.isFile()) continue;
    const name = e.name;
    if (name !== '.env' && !name.startsWith('.env.')) continue;
    if (name === '.env.example') continue; // committed template
    // must be gitignored (committed files already arrive via `git worktree add`)
    const check = spawnSync('git', ['-C', mainPath, 'check-ignore', name], {
      encoding: 'utf-8',
    });
    if (check.status === 0) out.push(name);
  }
  return out;
}

function hasSecret(content: string): boolean {
  return SECRET_PATTERNS.some((re) => re.test(content));
}

/**
 * Find the next free noVNC/VNC port pair by scanning existing worktrees'
 * `.devcontainer/.env` (mirrors Get-NextPorts in launch-worktree.ps1).
 */
export function nextDevcontainerPorts(mainPath: string): { noVnc: number; vnc: number } {
  const BASE_NOVNC = 6080;
  const BASE_VNC = 5900;
  let maxNoVnc = BASE_NOVNC;
  const wt = spawnSync('git', ['-C', mainPath, 'worktree', 'list', '--porcelain'], {
    encoding: 'utf-8',
  });
  const paths: string[] = [];
  for (const line of (wt.stdout || '').split('\n')) {
    const m = line.match(/^worktree (.+)$/);
    if (m) paths.push(m[1].trim());
  }
  for (const p of paths) {
    const envFile = path.join(p, '.devcontainer', '.env');
    try {
      const content = fs.readFileSync(envFile, 'utf-8');
      const m = content.match(/HOST_NOVNC_PORT=(\d+)/);
      if (m) maxNoVnc = Math.max(maxNoVnc, parseInt(m[1], 10));
    } catch {
      /* no env for this worktree */
    }
  }
  const noVnc = maxNoVnc + 1;
  return { noVnc, vnc: BASE_VNC + (noVnc - BASE_NOVNC) };
}

/** Regenerate `<worktree>/.devcontainer/.env` with unique ports (FR-10/FR-12). */
function regenerateDevcontainerEnv(mainPath: string, worktreePath: string): EnvSyncResult {
  const target = path.join(worktreePath, '.devcontainer', '.env');
  if (fs.existsSync(target)) {
    return { file: '.devcontainer/.env', action: 'skipped', secretDetected: false };
  }
  const ports = nextDevcontainerPorts(mainPath);
  const reposPath = path.dirname(mainPath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(
    target,
    `# Auto-generated by worktree-setup env-sync\nHOST_NOVNC_PORT=${ports.noVnc}\nHOST_VNC_PORT=${ports.vnc}\nHOST_REPOS_PATH=${reposPath}\n`,
  );
  return { file: '.devcontainer/.env', action: 'regenerated', secretDetected: false };
}

export interface EnvSyncReport {
  results: EnvSyncResult[];
  warnings: string[];
}

/**
 * Sync env/config files from `mainPath` into `worktreePath`.
 * Returns per-file results and human-facing warnings (e.g. secret files).
 */
export function syncEnvFiles(mainPath: string, worktreePath: string): EnvSyncReport {
  const results: EnvSyncResult[] = [];
  const warnings: string[] = [];

  // (1) Regenerate .devcontainer/.env (never copy — port collision).
  if (fs.existsSync(path.join(mainPath, '.devcontainer', '.env'))) {
    const r = regenerateDevcontainerEnv(mainPath, worktreePath);
    results.push(r);
    appendAudit(worktreePath, r);
  }

  // (2) Copy gitignored root .env* (minus excludes).
  for (const name of listCandidateEnvFiles(mainPath)) {
    const src = path.join(mainPath, name);
    const dest = path.join(worktreePath, name);
    if (fs.existsSync(dest)) {
      const r: EnvSyncResult = { file: name, action: 'skipped', secretDetected: false };
      results.push(r);
      appendAudit(worktreePath, r);
      continue;
    }
    try {
      const content = fs.readFileSync(src, 'utf-8');
      const secret = hasSecret(content);
      fs.copyFileSync(src, dest);
      const action: EnvSyncAction = secret ? 'warned' : 'copied';
      const r: EnvSyncResult = { file: name, action, secretDetected: secret };
      results.push(r);
      appendAudit(worktreePath, r);
      if (secret) {
        warnings.push(
          `[worktree-setup] Copied ${name} which appears to contain a secret — review before sharing the worktree.`,
        );
      }
    } catch (err) {
      warnings.push(`[worktree-setup] env-sync skipped ${name}: ${(err as Error).message}`);
    }
  }

  return { results, warnings };
}
