#!/usr/bin/env npx tsx
/**
 * context-menu postInstall script
 *
 * Windows only: installs Nilesoft Shell (if needed), creates claude-code.nss
 * with right-click entries for Claude Code (YOLO, YOLO+TUI, Normal).
 *
 * FR-1: Auto-install Nilesoft Shell via winget
 * FR-2: Global path to launch-claude-tui.ps1 via ~/.dev-pomogator/scripts/
 */

import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const PREFIX = '[context-menu]';
const NILESOFT_DIR = 'C:\\Program Files\\Nilesoft Shell';
const SHELL_NSS = path.join(NILESOFT_DIR, 'shell.nss');
const IMPORTS_DIR = path.join(NILESOFT_DIR, 'imports');
const CLAUDE_NSS = path.join(IMPORTS_DIR, 'claude-code.nss');
const IMPORT_LINE = "import 'imports/claude-code.nss'";

function log(message: string): void {
  console.log(`  ${PREFIX} ${message}`);
}

export function isWindows(): boolean {
  return process.platform === 'win32';
}

function isNilesoftInstalled(): boolean {
  return fs.existsSync(SHELL_NSS);
}

function installNilesoft(): boolean {
  log('Installing Nilesoft Shell via winget...');
  try {
    execSync(
      'winget install Nilesoft.NilesoftShell --accept-package-agreements --accept-source-agreements',
      { stdio: 'inherit', timeout: 120000 },
    );
    return fs.existsSync(SHELL_NSS);
  } catch {
    log('⚠ winget install failed. Install manually: winget install Nilesoft.NilesoftShell');
    return false;
  }
}

export function generateNss(): string {
  const launchScript = path.join(
    os.homedir(), '.dev-pomogator', 'scripts', 'launch-claude-tui.ps1',
  ).replace(/\//g, '\\');

  return `// Claude Code context menu entries (auto-generated by dev-pomogator)
// Reload: Ctrl+Right-click desktop → Shell → Reload

item(type='dir|back' sep='top' title='Claude Code (YOLO + TUI)' image='@app.dir\\imports\\claude-icon.ico' cmd='powershell.exe' args='-ExecutionPolicy Bypass -File "${launchScript}" -Yolo -ProjectDir "@sel.path"')
item(type='dir|back' title='Claude Code (YOLO)' image='@app.dir\\imports\\claude-icon.ico' cmd='wt.exe' args='-d "@sel.path" -- cmd /k claude --dangerously-skip-permissions')
item(type='dir|back' sep='bottom' title='Claude Code' image='@app.dir\\imports\\claude-icon.ico' cmd='wt.exe' args='-d "@sel.path" -- cmd /k claude')
`;
}

function elevatedCopy(src: string, dest: string): boolean {
  try {
    const srcEscaped = src.replace(/\//g, '\\');
    const destEscaped = dest.replace(/\//g, '\\');
    execSync(
      `powershell.exe -NoProfile -Command "Start-Process cmd -ArgumentList '/c copy /Y \\"${srcEscaped}\\" \\"${destEscaped}\\"' -Verb RunAs -Wait"`,
      { stdio: 'inherit', timeout: 30000 },
    );
    return true;
  } catch {
    return false;
  }
}

function ensureImportLine(): void {
  try {
    const content = fs.readFileSync(SHELL_NSS, 'utf-8');
    if (content.includes(IMPORT_LINE)) return;

    const updated = content.trimEnd() + '\n' + IMPORT_LINE + '\n';
    const tempFile = path.join(process.cwd(), 'temp-shell.nss');
    fs.writeFileSync(tempFile, updated, 'utf-8');

    if (elevatedCopy(tempFile, SHELL_NSS)) {
      log('✓ Added import to shell.nss');
    } else {
      log('⚠ Could not update shell.nss — add manually: ' + IMPORT_LINE);
    }

    try { fs.unlinkSync(tempFile); } catch { /* ignore */ }
  } catch {
    log('⚠ Could not read shell.nss');
  }
}

function main(): void {
  if (!isWindows()) {
    log('Skipped (not Windows)');
    return;
  }

  if (!isNilesoftInstalled()) {
    if (!installNilesoft()) {
      log('⚠ Nilesoft Shell not available — context menu not configured');
      return;
    }
  }

  const nssContent = generateNss();

  // Write temp → elevated copy
  const tempFile = path.join(process.cwd(), 'temp-claude-code.nss');
  fs.writeFileSync(tempFile, nssContent, 'utf-8');

  if (elevatedCopy(tempFile, CLAUDE_NSS)) {
    log('✓ Created claude-code.nss');
  } else {
    log('⚠ Elevated copy failed — run as admin or copy manually');
    log(`  Source: ${tempFile}`);
    log(`  Target: ${CLAUDE_NSS}`);
    return; // don't cleanup temp so user can copy manually
  }

  try { fs.unlinkSync(tempFile); } catch { /* ignore */ }

  ensureImportLine();
  log('✓ Context menu configured. Reload: Ctrl+Right-click desktop → Shell → Reload');
}

// Run only when invoked directly (not when imported for testing)
import { fileURLToPath } from 'node:url';
const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] === __filename) {
  main();
}
