#!/usr/bin/env npx tsx
/**
 * context-menu postInstall script
 *
 * Windows only: installs Nilesoft Shell when needed, creates separate Claude
 * and Codex NSS imports, and keeps both launch scripts in the global
 * ~/.dev-pomogator/scripts/ location referenced by the menu entries.
 *
 * FR-1: Auto-install Nilesoft Shell via winget.
 * FR-2/FR-8: Keep Claude and Codex as parallel context-menu channels.
 * FR-3/FR-10: Copy launch scripts to the global path referenced by NSS.
 */

import { execFileSync, execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const PREFIX = '[context-menu]';
export const NILESOFT_WINGET_ARGS = [
  'install',
  '--exact',
  '--id',
  'Nilesoft.Shell',
  '--source',
  'winget',
  '--accept-package-agreements',
  '--accept-source-agreements',
  '--disable-interactivity',
] as const;
const NILESOFT_DIR = 'C:\\Program Files\\Nilesoft Shell';
const SHELL_NSS = path.join(NILESOFT_DIR, 'shell.nss');
const IMPORTS_DIR = path.join(NILESOFT_DIR, 'imports');
const CLAUDE_NSS = path.join(IMPORTS_DIR, 'claude-code.nss');
const CODEX_NSS = path.join(IMPORTS_DIR, 'Codex.nss');
const CODEX_ICON = path.join(IMPORTS_DIR, 'codex-icon.ico');
const CLAUDE_IMPORT_LINE = "import 'imports/claude-code.nss'";
const CODEX_IMPORT_LINE = "import 'imports/Codex.nss'";

export type InstallMode = 'all' | 'codex-only';

export interface InstallPlan {
  mode: InstallMode;
  copyClaude: boolean;
  copyCodex: boolean;
  writeClaudeNss: boolean;
  writeCodexNss: boolean;
  writeCodexIcon: boolean;
  importLines: string[];
  nssFiles: string[];
  launchScripts: string[];
  iconFiles: string[];
}

// This module lives at <root>/tools/context-menu/postinstall.ts.
const MODULE_DIR = path.dirname(fileURLToPath(import.meta.url));

// The generated NSS entries point at these exact paths, so postinstall copies
// the bundled scripts here. User home is writable even when Program Files is not.
const GLOBAL_SCRIPTS_DIR = path.join(os.homedir(), '.dev-pomogator', 'scripts');
const GLOBAL_CLAUDE_LAUNCH_SCRIPT = path.join(GLOBAL_SCRIPTS_DIR, 'launch-claude-tui.ps1');
const GLOBAL_CODEX_LAUNCH_SCRIPT = path.join(GLOBAL_SCRIPTS_DIR, 'launch-Codex-tui.ps1');

function log(message: string): void {
  console.log(`  ${PREFIX} ${message}`);
}

function toWindowsPath(value: string): string {
  return value.replace(/\//g, '\\');
}

export function isWindows(): boolean {
  return process.platform === 'win32';
}

function isNilesoftInstalled(): boolean {
  return fs.existsSync(SHELL_NSS);
}

function installNilesoft(): boolean {
  log('Installing Nilesoft Shell via winget...');
  try {
    execFileSync('winget', [...NILESOFT_WINGET_ARGS], { stdio: 'inherit', timeout: 120000 });
    return fs.existsSync(SHELL_NSS);
  } catch {
    log(`winget install failed. Install manually: winget ${NILESOFT_WINGET_ARGS.join(' ')}`);
    return false;
  }
}

export function generateNss(): string {
  const launchScript = toWindowsPath(GLOBAL_CLAUDE_LAUNCH_SCRIPT);

  return `// Claude Code context menu entry (auto-generated by dev-pomogator)
// Reload: Ctrl+Right-click desktop -> Shell -> Reload

// Single entry by design: admin + --dangerously-skip-permissions + TUI.
// Routes through launch-claude-tui.ps1 so launch logging and workspace trust
// auto-grant happen before invoking Claude Code.
item(type='dir|back' admin=true title='Claude Code (YOLO + TUI)' cmd='powershell.exe' args='-ExecutionPolicy Bypass -File "${launchScript}" -Yolo -ProjectDir "@sel.dir"')
`;
}

export function generateCodexNss(): string {
  const launchScript = toWindowsPath(GLOBAL_CODEX_LAUNCH_SCRIPT);

  return `// Codex context menu entry (auto-generated by dev-pomogator)
// Reload: Ctrl+Right-click desktop -> Shell -> Reload

// Single entry by design: admin + Codex full-access flags, no TUI for the
// first supported Codex iteration.
// Routes through launch-Codex-tui.ps1 so launch logging and Codex project trust
// are handled before invoking codex.
item(type='dir|back' admin=true title='Codex (YOLO)' image='@app.dir\\imports\\codex-icon.ico' cmd='powershell.exe' args='-ExecutionPolicy Bypass -File "${launchScript}" -Yolo -NoTui -ProjectDir "@sel.dir"')
`;
}

export function parseInstallMode(argv = process.argv.slice(2)): InstallMode {
  return argv.includes('--codex-only') ? 'codex-only' : 'all';
}

export function installPlanForMode(mode: InstallMode = 'all'): InstallPlan {
  if (mode === 'codex-only') {
    return {
      mode,
      copyClaude: false,
      copyCodex: true,
      writeClaudeNss: false,
      writeCodexNss: true,
      writeCodexIcon: true,
      importLines: [CODEX_IMPORT_LINE],
      nssFiles: ['Codex.nss'],
      launchScripts: ['launch-Codex-tui.ps1'],
      iconFiles: ['codex-icon.ico'],
    };
  }

  return {
    mode,
    copyClaude: true,
    copyCodex: true,
    writeClaudeNss: true,
    writeCodexNss: true,
    writeCodexIcon: true,
    importLines: [CLAUDE_IMPORT_LINE, CODEX_IMPORT_LINE],
    nssFiles: ['claude-code.nss', 'Codex.nss'],
    launchScripts: ['launch-claude-tui.ps1', 'launch-Codex-tui.ps1'],
    iconFiles: ['codex-icon.ico'],
  };
}

export function generateShellImports(existingContent = '', mode: InstallMode = 'all'): string {
  const plan = installPlanForMode(mode);
  let content = existingContent.trimEnd();
  for (const line of plan.importLines) {
    if (!content.includes(line)) {
      content = content ? `${content}\n${line}` : line;
    }
  }
  return `${content}\n`;
}

/** Path to the Claude launch script bundled in the repo/plugin tree. */
export function bundledLaunchScriptPath(): string {
  return path.join(MODULE_DIR, '..', '..', 'scripts', 'launch-claude-tui.ps1');
}

/** Path to the Codex launch script bundled in the repo/plugin tree. */
export function bundledCodexLaunchScriptPath(): string {
  return path.join(MODULE_DIR, '..', '..', 'scripts', 'launch-Codex-tui.ps1');
}

/**
 * Copy the bundled Claude launch script to the global path referenced by NSS.
 * Returns false when the source is missing or the copy fails; postinstall stays
 * fail-soft so non-Windows/plugin install flows are not broken by context menu.
 */
export function copyLaunchScript(src?: string, dest?: string): boolean {
  const source = src ?? bundledLaunchScriptPath();
  const target = dest ?? GLOBAL_CLAUDE_LAUNCH_SCRIPT;
  return copyScript(source, target, 'Claude');
}

/** Copy the bundled Codex launch script to the global path referenced by NSS. */
export function copyCodexLaunchScript(src?: string, dest?: string): boolean {
  const source = src ?? bundledCodexLaunchScriptPath();
  const target = dest ?? GLOBAL_CODEX_LAUNCH_SCRIPT;
  return copyScript(source, target, 'Codex');
}

function copyScript(source: string, target: string, label: string): boolean {
  if (!fs.existsSync(source)) {
    log(`${label} launch script not found at ${source}`);
    return false;
  }

  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(source, target);
    log(`${label} launch script copied to ${target}`);
    return true;
  } catch (e) {
    log(`Could not copy ${label} launch script to ${target}: ${(e as Error).message}`);
    return false;
  }
}

function elevatedCopy(src: string, dest: string): boolean {
  try {
    const srcEscaped = toWindowsPath(src);
    const destEscaped = toWindowsPath(dest);
    execSync(
      `powershell.exe -NoProfile -Command "Start-Process cmd -ArgumentList '/c copy /Y \\"${srcEscaped}\\" \\"${destEscaped}\\"' -Verb RunAs -Wait"`,
      { stdio: 'inherit', timeout: 30000 },
    );
    return true;
  } catch {
    return false;
  }
}

function ensureImportLines(mode: InstallMode): boolean {
  try {
    const content = fs.readFileSync(SHELL_NSS, 'utf-8');
    const updated = generateShellImports(content, mode);
    if (updated === content) return false;

    const tempFile = path.join(process.cwd(), 'temp-shell.nss');
    fs.writeFileSync(tempFile, updated, 'utf-8');

    if (elevatedCopy(tempFile, SHELL_NSS)) {
      log(`Added ${installPlanForMode(mode).nssFiles.join(' and ')} imports to shell.nss`);
    } else {
      log(`Could not update shell.nss; add manually:\n${installPlanForMode(mode).importLines.join('\n')}`);
    }

    try { fs.unlinkSync(tempFile); } catch { /* ignore */ }
    return true;
  } catch {
    log('Could not read shell.nss');
    return false;
  }
}

function writeNssFile(target: string, content: string, label: string): boolean {
  let existingContent = '';
  try { existingContent = fs.readFileSync(target, 'utf-8'); } catch { /* file does not exist yet */ }
  if (existingContent === content) return false;

  const tempFile = path.join(process.cwd(), `temp-${path.basename(target)}`);
  fs.writeFileSync(tempFile, content, 'utf-8');

  if (elevatedCopy(tempFile, target)) {
    log(`Created ${label}`);
  } else {
    log(`Elevated copy failed for ${label}; run as admin or copy manually`);
    log(`  Source: ${tempFile}`);
    log(`  Target: ${target}`);
    return false;
  }

  try { fs.unlinkSync(tempFile); } catch { /* ignore */ }
  return true;
}

export function generateFallbackCodexIcon(): Buffer {
  const size = 32;
  const pixelBytes = size * size * 4;
  const maskBytes = size * 4;
  const dibBytes = 40 + pixelBytes + maskBytes;
  const icon = Buffer.alloc(6 + 16 + dibBytes);
  let offset = 0;

  icon.writeUInt16LE(0, offset); offset += 2; // reserved
  icon.writeUInt16LE(1, offset); offset += 2; // image type: icon
  icon.writeUInt16LE(1, offset); offset += 2; // image count

  icon.writeUInt8(size, offset++); // width
  icon.writeUInt8(size, offset++); // height
  icon.writeUInt8(0, offset++); // color count
  icon.writeUInt8(0, offset++); // reserved
  icon.writeUInt16LE(1, offset); offset += 2; // planes
  icon.writeUInt16LE(32, offset); offset += 2; // bit count
  icon.writeUInt32LE(dibBytes, offset); offset += 4;
  icon.writeUInt32LE(6 + 16, offset); offset += 4;

  icon.writeUInt32LE(40, offset); offset += 4; // BITMAPINFOHEADER size
  icon.writeInt32LE(size, offset); offset += 4;
  icon.writeInt32LE(size * 2, offset); offset += 4; // XOR + AND mask height
  icon.writeUInt16LE(1, offset); offset += 2;
  icon.writeUInt16LE(32, offset); offset += 2;
  icon.writeUInt32LE(0, offset); offset += 4; // BI_RGB
  icon.writeUInt32LE(pixelBytes, offset); offset += 4;
  icon.writeInt32LE(0, offset); offset += 4;
  icon.writeInt32LE(0, offset); offset += 4;
  icon.writeUInt32LE(0, offset); offset += 4;
  icon.writeUInt32LE(0, offset); offset += 4;

  const cx = 15.5;
  const cy = 15.5;
  const pixelOffset = 6 + 16 + 40;
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const dx = x - cx;
      const dy = y - cy;
      const distance = Math.sqrt(dx * dx + dy * dy);
      const angle = Math.atan2(dy, dx);
      const roundedSquare = Math.max(Math.abs(dx), Math.abs(dy)) <= 14;
      const cStroke = distance >= 8 && distance <= 12 && Math.abs(angle) > 0.62;
      const core = distance < 6;
      const sparkle = (x >= 21 && x <= 23 && y >= 8 && y <= 10) || (x === 22 && y >= 6 && y <= 12) || (y === 9 && x >= 19 && x <= 25);
      const row = size - 1 - y; // ICO DIB pixels are bottom-up.
      const i = pixelOffset + ((row * size + x) * 4);

      let r = 0;
      let g = 0;
      let b = 0;
      let a = roundedSquare ? 255 : 0;
      if (roundedSquare) {
        r = 15; g = 20; b = 28;
      }
      if (core) {
        r = 8; g = 13; b = 20;
      }
      if (cStroke) {
        r = 43; g = 214; b = 170;
      }
      if (sparkle) {
        r = 245; g = 249; b = 255; a = 255;
      }

      icon[i] = b;
      icon[i + 1] = g;
      icon[i + 2] = r;
      icon[i + 3] = a;
    }
  }

  return icon;
}

function uniquePaths(paths: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const candidate of paths) {
    const normalized = path.normalize(candidate);
    const key = process.platform === 'win32' ? normalized.toLowerCase() : normalized;
    if (!seen.has(key)) {
      seen.add(key);
      result.push(normalized);
    }
  }
  return result;
}

export function codexExecutableCandidates(env: NodeJS.ProcessEnv = process.env): string[] {
  const candidates: string[] = [];
  if (env.LOCALAPPDATA) {
    candidates.push(path.join(env.LOCALAPPDATA, 'Programs', 'OpenAI', 'Codex', 'bin', 'codex.exe'));
  }

  const pathEntries = (env.PATH ?? '').split(path.delimiter).filter(Boolean);
  for (const entry of pathEntries) {
    candidates.push(path.join(entry, process.platform === 'win32' ? 'codex.exe' : 'codex'));
  }

  return uniquePaths(candidates);
}

export function codexIconFileCandidates(env: NodeJS.ProcessEnv = process.env): string[] {
  const candidates: string[] = [];
  if (env.LOCALAPPDATA) {
    candidates.push(path.join(env.LOCALAPPDATA, 'Programs', 'OpenAI', 'Codex', 'resources', 'icon.ico'));
    candidates.push(path.join(env.LOCALAPPDATA, 'Programs', 'OpenAI', 'Codex', 'app', 'resources', 'icon.ico'));
  }

  const windowsApps = env.ProgramFiles ? path.join(env.ProgramFiles, 'WindowsApps') : '';
  if (windowsApps) {
    try {
      for (const entry of fs.readdirSync(windowsApps, { withFileTypes: true })) {
        if (entry.isDirectory() && /^OpenAI\.Codex_/i.test(entry.name)) {
          candidates.push(path.join(windowsApps, entry.name, 'app', 'resources', 'icon.ico'));
          candidates.push(path.join(windowsApps, entry.name, 'app', 'resources', 'codex-tray.ico'));
        }
      }
    } catch { /* WindowsApps may be unreadable */ }
  }

  return uniquePaths(candidates);
}

function dynamicCodexIconFileCandidates(env: NodeJS.ProcessEnv = process.env): string[] {
  const candidates = codexIconFileCandidates(env);
  const appxLocation = codexAppxInstallLocation();
  if (appxLocation) {
    candidates.push(path.join(appxLocation, 'app', 'resources', 'icon.ico'));
    candidates.push(path.join(appxLocation, 'app', 'resources', 'codex-tray.ico'));
  }
  return uniquePaths(candidates);
}

function dynamicCodexExecutableCandidates(env: NodeJS.ProcessEnv = process.env): string[] {
  const candidates = codexExecutableCandidates(env);

  if (env.LOCALAPPDATA) {
    const localCodexBin = path.join(env.LOCALAPPDATA, 'OpenAI', 'Codex', 'bin');
    try {
      for (const entry of fs.readdirSync(localCodexBin, { withFileTypes: true })) {
        if (entry.isDirectory()) {
          candidates.push(path.join(localCodexBin, entry.name, 'codex.exe'));
        }
      }
    } catch { /* optional Codex install layout */ }
  }

  const windowsApps = env.ProgramFiles ? path.join(env.ProgramFiles, 'WindowsApps') : '';
  if (windowsApps) {
    try {
      for (const entry of fs.readdirSync(windowsApps, { withFileTypes: true })) {
        if (entry.isDirectory() && /^OpenAI\.Codex_/i.test(entry.name)) {
          candidates.push(path.join(windowsApps, entry.name, 'app', 'Codex.exe'));
          candidates.push(path.join(windowsApps, entry.name, 'app', 'resources', 'codex.exe'));
        }
      }
    } catch { /* WindowsApps may be unreadable */ }
  }

  return uniquePaths(candidates);
}

function isUsableIco(filePath: string): boolean {
  try {
    const bytes = fs.readFileSync(filePath);
    if (bytes.length < 22) return false;
    return (
      bytes.readUInt16LE(0) === 0 &&
      bytes.readUInt16LE(2) === 1 &&
      bytes.readUInt16LE(4) >= 1 &&
      bytes.readUInt32LE(14) > 0 &&
      bytes.readUInt32LE(18) < bytes.length
    );
  } catch {
    return false;
  }
}

export function findInstalledCodexIconFile(env: NodeJS.ProcessEnv = process.env): string | null {
  return dynamicCodexIconFileCandidates(env).find((candidate) => isUsableIco(candidate)) ?? null;
}

export function findInstalledCodexExecutable(env: NodeJS.ProcessEnv = process.env): string | null {
  return dynamicCodexExecutableCandidates(env).find((candidate) => fs.existsSync(candidate)) ?? null;
}

function codexAppxInstallLocation(): string | null {
  if (process.platform !== 'win32') return null;

  try {
    const stdout = execFileSync(
      'powershell.exe',
      ['-NoProfile', '-Command', '(Get-AppxPackage OpenAI.Codex | Select-Object -First 1 -ExpandProperty InstallLocation)'],
      { encoding: 'utf8', stdio: 'pipe', timeout: 10000 },
    ).trim();
    return stdout || null;
  } catch {
    return null;
  }
}

function extractAssociatedIcon(exePath: string, targetPath: string): boolean {
  const script = [
    "$ErrorActionPreference = 'Stop'",
    'Add-Type -AssemblyName System.Drawing',
    '$icon = [System.Drawing.Icon]::ExtractAssociatedIcon($env:CODEX_EXE)',
    "if ($null -eq $icon) { throw 'No associated icon found' }",
    '$stream = [System.IO.File]::Create($env:CODEX_ICON_OUT)',
    'try { $icon.Save($stream) } finally { $stream.Dispose(); $icon.Dispose() }',
  ].join('; ');

  try {
    execFileSync('powershell.exe', ['-NoProfile', '-Command', script], {
      env: { ...process.env, CODEX_EXE: exePath, CODEX_ICON_OUT: targetPath },
      stdio: 'pipe',
      timeout: 15000,
    });
    return fs.existsSync(targetPath) && fs.statSync(targetPath).size > 100;
  } catch {
    return false;
  }
}

function ensureCodexIcon(): boolean {
  const tempFile = path.join(process.cwd(), 'temp-codex-icon.ico');
  const officialIcon = findInstalledCodexIconFile();
  const officialExe = officialIcon ? null : findInstalledCodexExecutable();
  let source = 'generated fallback icon';

  if (officialIcon) {
    fs.copyFileSync(officialIcon, tempFile);
    source = `installed OpenAI Codex resource icon (${officialIcon})`;
  } else if (officialExe && extractAssociatedIcon(officialExe, tempFile) && isUsableIco(tempFile)) {
    source = `installed OpenAI Codex executable icon (${officialExe})`;
  } else if (isUsableIco(CODEX_ICON)) {
    return false;
  } else {
    fs.writeFileSync(tempFile, generateFallbackCodexIcon());
  }

  if (fs.existsSync(CODEX_ICON)) {
    const existing = fs.readFileSync(CODEX_ICON);
    const next = fs.readFileSync(tempFile);
    if (existing.equals(next)) {
      try { fs.unlinkSync(tempFile); } catch { /* ignore */ }
      return false;
    }
  }

  if (elevatedCopy(tempFile, CODEX_ICON)) {
    log(`Created codex-icon.ico from ${source}`);
  } else {
    log('Elevated copy failed for codex-icon.ico; run as admin or copy manually');
    log(`  Source: ${tempFile}`);
    log(`  Target: ${CODEX_ICON}`);
    return false;
  }

  try { fs.unlinkSync(tempFile); } catch { /* ignore */ }
  return true;
}

function reloadNilesoft(): void {
  const shellExe = path.join(NILESOFT_DIR, 'shell.exe');

  try {
    execSync(`"${shellExe}" -restart`, { stdio: 'pipe', timeout: 10000 });
    log('Nilesoft Shell reloaded');
  } catch {
    try {
      execSync(
        `powershell.exe -NoProfile -Command "Start-Process '${shellExe}' -ArgumentList '-restart' -Verb RunAs -Wait"`,
        { stdio: 'pipe', timeout: 10000 },
      );
      log('Nilesoft Shell reloaded elevated');
    } catch {
      log('Reload failed; will ensure Explorer is running');
    }
  }

  ensureExplorerRunning();
}

function ensureExplorerRunning(): void {
  try {
    execSync(
      'powershell.exe -NoProfile -Command "if (-not (Get-Process explorer -EA SilentlyContinue)) { Start-Process explorer.exe }"',
      { encoding: 'utf-8', stdio: 'pipe', timeout: 5000 },
    );
  } catch { /* best-effort */ }
}

function main(): void {
  const mode = parseInstallMode();
  const plan = installPlanForMode(mode);

  if (!isWindows()) {
    log('Skipped (not Windows)');
    return;
  }

  if (!isNilesoftInstalled()) {
    if (!installNilesoft()) {
      log('Nilesoft Shell not available; context menu not configured');
      return;
    }
  }

  const claudeScriptReady = plan.copyClaude ? copyLaunchScript() : true;
  const codexScriptReady = plan.copyCodex ? copyCodexLaunchScript() : true;
  if (!claudeScriptReady || !codexScriptReady) {
    log('Launch scripts are incomplete; NSS files and shell imports were not changed');
    return;
  }

  const claudeChanged = plan.writeClaudeNss
    ? writeNssFile(CLAUDE_NSS, generateNss(), 'claude-code.nss')
    : false;
  const codexChanged = plan.writeCodexNss
    ? writeNssFile(CODEX_NSS, generateCodexNss(), 'Codex.nss')
    : false;
  const codexIconChanged = plan.writeCodexIcon ? ensureCodexIcon() : false;
  const importsChanged = ensureImportLines(mode);

  if (claudeChanged || codexChanged || codexIconChanged || importsChanged) {
    reloadNilesoft();
    log('Context menu configured and reloaded');
  } else {
    log('Context menu already up to date');
  }
}

const __filename = fileURLToPath(import.meta.url);
if (path.basename(process.argv[1] ?? '') === 'postinstall.ts' && process.argv[1] === __filename) {
  main();
}
